"""Nuendo Live 3 .nlpr exporter for MultitrackSession (Phase 4 / v2.0).

References:
- multitrack_session_builder_spec.md §"Nuendo Live (.nlpr)" (lines 187-310)
  — XML structure, Farb palette, template-injection algorithm,
  "things NOT to touch" list.
- .planning/phases/04-nuendo-live-export/04-RESEARCH.md — lxml mechanics,
  pitfalls (auth match, three-place form gate, CRLF tolerance,
  surrogate-pair guards), and the locked D-08 ID allocator.
- .planning/phases/04-nuendo-live-export/04-CONTEXT.md D-01..D-10 — locked
  decisions for fixture lifecycle, color → Farb mapping, ID generation,
  and "all IDs replaced for every track."

Trust boundary note: this module does NOT filter sessions by project.
The caller (Phase 4 view at planner/views.py: multitrack_export_nlpr)
is responsible for verifying the session belongs to the current
project. This module trusts its input and is intentionally a pure
bytes-builder with no DB writes.
"""
from __future__ import annotations

import copy
from pathlib import Path

from lxml import etree

from .reaper_export import _ordered_enabled_tracks

# ──────────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────────

# CONTEXT.md D-07: Yamaha palette name → Nuendo Farb index. 'Off' and
# 'White' are intentionally OMITTED from the dict so dict.get() returns
# None for them; the exporter strips the <int name='Farb'/> element from
# the deep-copied subtree (D-05).
YAMAHA_TO_FARB = {
    'Red':      0,
    'Orange':   1,
    'Yellow':   2,
    'Green':    5,
    'Sky Blue': 8,
    'Blue':     10,
    'Purple':   12,
    'Pink':     14,
}

# Bundled template fixture. Generated by Charlie (Phase 4 Plan 03 / D-02)
# on Windows + Nuendo Live 3. Read-only at runtime.
_TEMPLATE_PATH = (
    Path(__file__).parent.parent / 'data' / 'multitrack'
    / 'nuendo_live_3_template.nlpr'
)

# Module-level cache; populated by _load_template() on first call. We
# cache the parsed ElementTree and deepcopy the root per export so the
# cache never sees mutations (Pitfall 3).
_TEMPLATE_TREE: etree._ElementTree | None = None

# ──────────────────────────────────────────────────────────────────
# Errors
# ──────────────────────────────────────────────────────────────────


class ExportTemplateError(Exception):
    """Raised when the bundled .nlpr template is missing, malformed, or
    does not contain exactly one Audio MFolderTrack with a single seed
    MAudioTrackEvent. Caught by the view layer (D-03) which renders
    editor.html with an export_error banner instead of returning 500.
    """


# ──────────────────────────────────────────────────────────────────
# Template loading
# ──────────────────────────────────────────────────────────────────


def _load_template():
    """Return a deepcopy of the bundled template root.

    Parses the template once and caches the parsed tree. Each caller
    gets a deepcopy so mutations never leak back into the cache
    (RESEARCH Pitfall 3).
    """
    global _TEMPLATE_TREE
    if _TEMPLATE_TREE is None:
        if not _TEMPLATE_PATH.exists():
            raise ExportTemplateError(
                f'Nuendo Live template missing: {_TEMPLATE_PATH}'
            )
        try:
            _TEMPLATE_TREE = etree.parse(str(_TEMPLATE_PATH))
        except etree.XMLSyntaxError as exc:
            raise ExportTemplateError(
                f'Nuendo Live template malformed: {exc}'
            ) from exc
    return copy.deepcopy(_TEMPLATE_TREE.getroot())


# ──────────────────────────────────────────────────────────────────
# Private helpers — Task 2 implements bodies
# ──────────────────────────────────────────────────────────────────


def _find_audio_folder(root):
    """RESEARCH Pattern 2 — locate <obj class='MFolderTrack'> whose
    inner Name is 'Audio' (NOT 'Input/Output Channels').
    """
    folders = root.xpath(
        ".//obj[@class='MFolderTrack']"
        "[.//string[@name='Name' and @value='Audio']]"
    )
    if not folders:
        raise ExportTemplateError(
            "No MFolderTrack named 'Audio' found in template"
        )
    if len(folders) > 1:
        raise ExportTemplateError(
            f"Multiple Audio folders found ({len(folders)})"
        )
    return folders[0]


def _scan_max_id(root):
    """D-08: find the largest integer ID anywhere in the document.

    Scans:
      - every element with an @ID attribute (covers <obj ID='N'/>)
      - every <int name='RuntimeID' value='N'/>
      - every <int name='ID' value='N'/>
    Returns 0 if no IDs found (defensive — should never happen on a
    real Nuendo template).
    """
    ids: list[int] = []
    for elem in root.xpath("//*[@ID]"):
        try:
            ids.append(int(elem.get('ID')))
        except (TypeError, ValueError):
            pass
    for elem in root.xpath("//int[@name='RuntimeID' or @name='ID']"):
        try:
            ids.append(int(elem.get('value')))
        except (TypeError, ValueError):
            pass
    return max(ids) if ids else 0


def _replace_all_ids(new_track, next_id):
    """D-10: replace every @ID attribute and every RuntimeID / ID
    int-value inside `new_track` with sequentially-allocated fresh IDs.

    Order of replacement (matters only for determinism — the IDs all
    end up unique either way):
      1. The new_track root's own @ID (if present).
      2. Every descendant element with an @ID attribute.
      3. Every <int name='RuntimeID' value='...'/> descendant.
      4. Every <int name='ID' value='...'/> descendant.

    Returns the next available ID after consuming for this track.
    """
    if new_track.get('ID') is not None:
        new_track.set('ID', str(next_id))
        next_id += 1
    for elem in new_track.xpath(".//*[@ID]"):
        elem.set('ID', str(next_id))
        next_id += 1
    for elem in new_track.xpath(
        ".//int[@name='RuntimeID' or @name='ID']"
    ):
        elem.set('value', str(next_id))
        next_id += 1
    return next_id


def _set_names(new_track, label):
    """RESEARCH Pitfall 9 — write `label` into BOTH name elements:
      - outer  <obj class='MListNode'>/<string name='Name' wide='true'/>
      - inner  ...MAudioTrack//DeviceAttributes/Name/<string
               name='String' wide='true'/>

    Raises ExportTemplateError if either element is missing.
    """
    outer = new_track.find(
        "./obj[@class='MListNode']/string[@name='Name']"
    )
    if outer is None:
        raise ExportTemplateError(
            "Seed track missing outer MListNode/Name string"
        )
    outer.set('value', label)

    inner = new_track.find(
        ".//obj[@class='MAudioTrack']"
        "//member[@name='DeviceAttributes']"
        "/member[@name='Name']"
        "/string[@name='String']"
    )
    if inner is None:
        raise ExportTemplateError(
            "Seed track missing inner DeviceAttributes/Name/String"
        )
    inner.set('value', label)


def _set_channel_id(new_track, index_1_based):
    """Spec lines 224, 292 — Channel ID is the 1-based track index."""
    ch = new_track.find(
        ".//obj[@class='MAudioTrack']/int[@name='Channel ID']"
    )
    if ch is None:
        raise ExportTemplateError(
            "Seed MAudioTrack missing <int name='Channel ID'/>"
        )
    ch.set('value', str(index_1_based))


def _apply_farb(new_track, yamaha_name):
    """D-05/D-07 — set Farb to YAMAHA_TO_FARB[name] or remove the
    element entirely.

    Rules:
      - yamaha_name is None or absent from YAMAHA_TO_FARB → remove
        <int name='Farb'/> entirely. Nuendo Live falls back to default
        appearance (D-05).
      - yamaha_name is in YAMAHA_TO_FARB → mutate the existing
        <int name='Farb'/> value. If the seed template doesn't have a
        Farb element (RESEARCH A5 — depends on Charlie's fixture),
        create one as a child of <member name='Additional Attributes'>.
    """
    farb = new_track.find(
        ".//member[@name='Additional Attributes']/int[@name='Farb']"
    )
    if yamaha_name is None or yamaha_name not in YAMAHA_TO_FARB:
        if farb is not None:
            farb.getparent().remove(farb)
        return
    if farb is None:
        attrs = new_track.find(
            ".//member[@name='Additional Attributes']"
        )
        if attrs is None:
            raise ExportTemplateError(
                "Seed track missing <member name='Additional Attributes'>"
            )
        farb = etree.SubElement(attrs, 'int', {'name': 'Farb'})
    farb.set('value', str(YAMAHA_TO_FARB[yamaha_name]))


def _sanitize_label(label):
    """RESEARCH Pitfall 4 — strip XML-incompatible control chars from a
    track label before handing to lxml's .set(). lxml raises
    ValueError on NUL bytes etc.; this guard prevents the exporter
    from crashing on pathological label data.
    """
    if not label:
        return '(untitled)'
    # Strip C0 control chars except \t (0x09), \n (0x0A), \r (0x0D).
    cleaned = ''.join(
        ch for ch in label
        if ch in '\t\n\r' or (0x20 <= ord(ch) <= 0xD7FF)
        or (0xE000 <= ord(ch) <= 0xFFFD)
    )
    return cleaned or '(untitled)'


# ──────────────────────────────────────────────────────────────────
# Public builder
# ──────────────────────────────────────────────────────────────────


def build_nlpr(session) -> bytes:
    """Generate a Nuendo Live 3 .nlpr file as UTF-8 bytes.

    Algorithm (RESEARCH Pattern 1 / spec §template-injection):
      1. Load the bundled template (cached, deepcopy per call).
      2. Locate the Audio MFolderTrack and its single seed
         <obj class='MAudioTrackEvent'>.
      3. Compute the next free ID as max(existing) + 1000 (D-08).
      4. For each enabled track in session order:
            a. deepcopy the seed
            b. replace every ID/RuntimeID with sequential fresh IDs
            c. set both Name elements to the resolved label
            d. set Channel ID to the 1-based index
            e. apply or strip Farb per resolved_yamaha_name
            f. append to the <list> alongside the seed
      5. Remove the seed (D-10 — every output track is generated
         identically; the seed never appears in the output).
      6. Serialize via etree.tostring with xml_declaration=True,
         encoding='utf-8'.

    Returns bytes (NOT str). The view layer wraps in HttpResponse with
    content_type='application/xml; charset=utf-8'.

    Raises:
        ExportTemplateError — bundled fixture missing / malformed /
            doesn't parse to exactly one Audio MFolderTrack with a
            single seed MAudioTrackEvent. Caller catches and renders
            editor.html with export_error (D-03).
    """
    root = _load_template()
    audio_folder = _find_audio_folder(root)

    track_list = audio_folder.find(".//list[@name='Tracks']")
    if track_list is None:
        raise ExportTemplateError(
            "Audio MFolderTrack has no <list name='Tracks'> child"
        )
    seed_tracks = track_list.findall("./obj[@class='MAudioTrackEvent']")
    if len(seed_tracks) != 1:
        raise ExportTemplateError(
            f"Template Audio folder must contain exactly 1 "
            f"MAudioTrackEvent seed (found {len(seed_tracks)})"
        )
    seed_track = seed_tracks[0]

    next_id = _scan_max_id(root) + 1000

    enabled_tracks = _ordered_enabled_tracks(session)
    for n, mt_track in enumerate(enabled_tracks, start=1):
        new_track = copy.deepcopy(seed_track)
        next_id = _replace_all_ids(new_track, next_id)
        _set_names(new_track, _sanitize_label(mt_track.resolved_label))
        _set_channel_id(new_track, n)
        _apply_farb(new_track, mt_track.resolved_yamaha_name)
        track_list.append(new_track)

    # D-10: drop the seed AFTER the loop so its IDs never appear in the
    # output. Every output track came from the sequential allocator.
    track_list.remove(seed_track)

    return etree.tostring(root, xml_declaration=True, encoding='utf-8')
