# Generated by Django 5.2.4 on 2026-01-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('demo', 'Request a Demo'), ('support', 'Support'), ('partnership', 'Partnership'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this inquiry')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g., A1, Audio Engineer, Production Manager', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waitlist Signup',
                'verbose_name_plural': 'Waitlist Signups',
                'ordering': ['-created_at'],
            },
        ),
    ]
