# Generated by Django 5.2.4 on 2025-07-18 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inputs', models.IntegerField()),
                ('outputs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatchInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dante_number', models.CharField(blank=True, max_length=10)),
                ('callisto_sl', models.CharField(blank=True, max_length=10)),
                ('callisto_sr', models.CharField(blank=True, max_length=10)),
                ('callisto', models.CharField(blank=True, max_length=10)),
                ('input_channel', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('dca', models.CharField(blank=True, max_length=10)),
                ('mute', models.CharField(blank=True, max_length=10)),
                ('direct_out', models.CharField(blank=True, max_length=100)),
                ('omni_in', models.CharField(blank=True, max_length=10)),
                ('omni_out', models.CharField(blank=True, max_length=10)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='planner.console')),
            ],
        ),
        migrations.CreateModel(
            name='PatchOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('mono_st', models.CharField(blank=True, max_length=10)),
                ('bus_type', models.CharField(blank=True, max_length=50)),
                ('pre_post', models.CharField(blank=True, max_length=50)),
                ('omni_in', models.CharField(blank=True, max_length=10)),
                ('omni_out', models.CharField(blank=True, max_length=10)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='planner.console')),
            ],
        ),
    ]
