# Generated by Django 5.2.4 on 2025-07-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchoutput',
            name='console',
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='planner.console')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='planner.console')),
            ],
        ),
        migrations.DeleteModel(
            name='PatchInput',
        ),
        migrations.DeleteModel(
            name='PatchOutput',
        ),
    ]
