# Generated by Django 5.2.4 on 2025-07-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_patchoutput_console_input_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='dante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='dca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='direct_out',
            field=models.CharField(blank=True, max_length=100, verbose_name='Direct Out'),
        ),
        migrations.AddField(
            model_name='input',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='input_ch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Input Ch'),
        ),
        migrations.AddField(
            model_name='input',
            name='mute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='input',
            name='omni_in',
            field=models.CharField(blank=True, max_length=100, verbose_name='Omni In'),
        ),
        migrations.AddField(
            model_name='input',
            name='omni_out',
            field=models.CharField(blank=True, max_length=100, verbose_name='Omni Out'),
        ),
        migrations.AddField(
            model_name='input',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='output',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
