# Generated by Django 5.2.4 on 2025-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_input_dante_input_dca_input_direct_out_input_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='input',
            name='console',
        ),
        migrations.RemoveField(
            model_name='input',
            name='dante',
        ),
        migrations.RemoveField(
            model_name='input',
            name='dca',
        ),
        migrations.RemoveField(
            model_name='input',
            name='device',
        ),
        migrations.RemoveField(
            model_name='input',
            name='group',
        ),
        migrations.RemoveField(
            model_name='input',
            name='input_ch',
        ),
        migrations.RemoveField(
            model_name='input',
            name='label',
        ),
        migrations.RemoveField(
            model_name='input',
            name='output',
        ),
        migrations.RemoveField(
            model_name='input',
            name='source',
        ),
        migrations.AlterField(
            model_name='input',
            name='mute',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
