# Generated by Django 5.2.4 on 2025-07-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_input_channel_remove_input_console_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='console',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='planner.console'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='dante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='dca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='input_ch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Input Ch'),
        ),
        migrations.AddField(
            model_name='input',
            name='output',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
