# Generated by Django 5.2.4 on 2025-07-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_input_console_input_dante_input_dca_input_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='dante',
            new_name='dante_number',
        ),
    ]
