# Generated by Django 5.2.4 on 2025-07-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_rename_dante_to_dante_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dante_number', models.PositiveIntegerField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(blank=True, max_length=50)),
                ('dca', models.CharField(blank=True, max_length=50)),
                ('mute', models.BooleanField(default=False)),
                ('direct_out', models.CharField(blank=True, max_length=100)),
                ('omni_in', models.CharField(blank=True, max_length=100)),
                ('omni_out', models.CharField(blank=True, max_length=100)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='planner.console')),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_label', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('routing', models.CharField(blank=True, max_length=100)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='planner.console')),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.RemoveField(
            model_name='output',
            name='console',
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
    ]
