# Generated by Django 5.2.4 on 2025-07-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_consoleinput_consoleoutput_delete_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consoleinput',
            old_name='channel',
            new_name='input_ch',
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='mute',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
