# Generated by Django 5.2.4 on 2025-07-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_rename_channel_consoleinput_input_ch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consoleinput',
            old_name='input_ch',
            new_name='channel',
        ),
    ]
