# Generated by Django 5.2.4 on 2025-07-24 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_rename_input_ch_consoleinput_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='consoleinput',
            name='channel',
        ),
        migrations.AddField(
            model_name='consoleinput',
            name='input_ch',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.console'),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='dante_number',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='dca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='mute',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ConsoleAuxOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aux_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('mono_stereo', models.CharField(choices=[('Mono', 'Mono'), ('Stereo', 'Stereo')], max_length=10, verbose_name='Mono/Stereo')),
                ('bus_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable')], max_length=10, verbose_name='Fixed/Variable')),
                ('omni_in', models.CharField(blank=True, max_length=100)),
                ('omni_out', models.CharField(blank=True, max_length=100)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.console')),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleMatrixOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('mono_stereo', models.CharField(choices=[('Mono', 'Mono'), ('Stereo', 'Stereo')], max_length=10)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('omni_out', models.CharField(blank=True, max_length=100)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.console')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_label', models.CharField(max_length=20)),
                ('signal_name', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='planner.device')),
            ],
        ),
        migrations.DeleteModel(
            name='ConsoleOutput',
        ),
    ]
