# Generated by Django 5.2.4 on 2025-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_device_remove_consoleinput_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoleauxoutput',
            name='bus_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Variable', 'Variable')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consoleauxoutput',
            name='mono_stereo',
            field=models.CharField(blank=True, choices=[('Mono', 'Mono'), ('Stereo', 'Stereo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consoleauxoutput',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='dante_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='dca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='direct_out',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='input_ch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='mute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='omni_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='omni_out',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consolematrixoutput',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consolematrixoutput',
            name='mono_stereo',
            field=models.CharField(blank=True, choices=[('Mono', 'Mono'), ('Stereo', 'Stereo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consolematrixoutput',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consolematrixoutput',
            name='omni_out',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
