# Generated by Django 5.2.4 on 2025-07-24 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_consoleauxoutput_bus_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinput',
            name='input_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeviceOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_number', models.PositiveIntegerField()),
                ('signal_name', models.CharField(default='OUT', max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='planner.device')),
            ],
        ),
    ]
