# Generated by Django 5.2.4 on 2025-07-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_deviceinput_input_number_deviceoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceoutput',
            name='signal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
