# Generated by Django 5.2.4 on 2025-07-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_deviceoutput_signal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinput',
            name='input_label',
        ),
    ]
