# Generated by Django 5.2.4 on 2025-07-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_remove_deviceinput_input_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='input_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='output_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
