# Generated by Django 5.2.4 on 2025-07-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_device_input_count_device_output_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinput',
            name='input_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceoutput',
            name='output_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
