# Generated by Django 5.2.4 on 2025-07-27 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_alter_deviceinput_input_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinput',
            name='console_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_inputs', to='planner.consoleinput'),
        ),
    ]
