# Generated by Django 5.2.4 on 2025-07-27 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_deviceinput_console_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceoutput',
            name='console_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.consoleauxoutput'),
        ),
    ]
