# Generated by Django 5.2.4 on 2025-07-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_deviceoutput_console_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinput',
            name='signal_name',
        ),
        migrations.RemoveField(
            model_name='deviceoutput',
            name='console_output',
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceinput',
            name='console_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.consoleinput'),
        ),
        migrations.AlterField(
            model_name='deviceinput',
            name='input_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='deviceoutput',
            name='output_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='deviceoutput',
            name='signal_name',
            field=models.CharField(max_length=100),
        ),
    ]
