# Generated by Django 5.2.4 on 2025-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_remove_deviceinput_signal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinput',
            name='console_input',
        ),
        migrations.AddField(
            model_name='deviceinput',
            name='signal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deviceoutput',
            name='signal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
