# Generated by Django 5.2.4 on 2025-07-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_remove_deviceinput_console_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinput',
            name='signal_name',
            field=models.CharField(max_length=100),
        ),
    ]
