# Generated by Django 5.2.4 on 2025-07-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_alter_deviceinput_signal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinput',
            name='input_number',
        ),
        migrations.AddField(
            model_name='deviceinput',
            name='console_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_inputs', to='planner.consoleinput'),
        ),
        migrations.AddField(
            model_name='deviceinput',
            name='iinput_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceoutput',
            name='console_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_outputs', to='planner.consoleauxoutput'),
        ),
        migrations.AlterField(
            model_name='deviceoutput',
            name='output_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
