# Generated by Django 5.2.4 on 2025-07-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_remove_deviceinput_input_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinput',
            old_name='iinput_number',
            new_name='input_number',
        ),
    ]
