# Generated by Django 5.2.4 on 2025-07-29 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_rename_iinput_number_deviceinput_input_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., HL LA Racks, HR LA Racks, Monitor World', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('HL', 'House Left'), ('HR', 'House Right'), ('MONITOR', 'Monitor World'), ('DELAY', 'Delay Towers'), ('FILL', 'Front Fill'), ('OTHER', 'Other Location')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amp Location',
                'verbose_name_plural': 'Amp Locations',
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Amp identifier or model name', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='Network IP address')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_count', models.PositiveIntegerField(default=4, help_text='Number of output channels')),
                ('avb_stream_input', models.CharField(blank=True, help_text='AVB stream source', max_length=50, null=True)),
                ('xlr_input_count', models.PositiveIntegerField(default=0, help_text='Number of XLR inputs')),
                ('analogue_input_count', models.PositiveIntegerField(default=0, help_text='Number of analogue inputs')),
                ('aes_input_count', models.PositiveIntegerField(default=0, help_text='Number of AES inputs')),
                ('nl4_outputs', models.PositiveIntegerField(default=0, help_text='Number of NL4 outputs')),
                ('cacom_output', models.BooleanField(default=False, help_text='Has Cacom output')),
                ('preset_name', models.CharField(blank=True, help_text='Active preset', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amps', to='planner.amplocation')),
            ],
            options={
                'verbose_name': 'Amp',
                'verbose_name_plural': 'Amps',
                'ordering': ['location', 'ip_address'],
                'unique_together': {('location', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='AmpChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.PositiveIntegerField()),
                ('channel_name', models.CharField(blank=True, help_text='e.g., Left, Right, Center, Sub, Front Fill, Delay, Foldback', max_length=100, null=True)),
                ('avb_stream', models.CharField(blank=True, max_length=50, null=True)),
                ('xlr_input', models.CharField(blank=True, max_length=50, null=True)),
                ('analogue_input', models.CharField(blank=True, max_length=50, null=True)),
                ('aes_input', models.CharField(blank=True, max_length=50, null=True)),
                ('nl4_output', models.CharField(blank=True, max_length=50, null=True)),
                ('cacom_output', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='planner.amp')),
            ],
            options={
                'verbose_name': 'Amp Channel',
                'verbose_name_plural': 'Amp Channels',
                'ordering': ['amp', 'channel_number'],
                'unique_together': {('amp', 'channel_number')},
            },
        ),
    ]
