# Generated by Django 5.2.4 on 2025-07-31 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_amplocation_amp_ampchannel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmpLocation',
            new_name='Location',
        ),
    ]
