# Generated by Django 5.2.4 on 2025-07-31 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_rename_amplocation_to_location'),
    ]

    operations = [
    ]
