# Generated by Django 5.2.4 on 2025-07-31 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_update_location_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
    ]
