# Generated by Django 5.2.4 on 2025-08-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0027_alter_location_options_remove_location_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampchannel',
            name='xlr_input',
        ),
    ]
