# Generated by Django 5.2.4 on 2025-08-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0028_remove_ampchannel_xlr_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amp',
            name='nl4_outputs',
        ),
    ]
