# Generated by Django 5.2.4 on 2025-08-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0029_remove_amp_nl4_outputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampchannel',
            name='nl4_output',
        ),
        migrations.AddField(
            model_name='ampchannel',
            name='nl4_pair_1',
            field=models.CharField(blank=True, help_text='NL4 connector pair 1 +/- assignment', max_length=50, null=True, verbose_name='1 +/-'),
        ),
        migrations.AddField(
            model_name='ampchannel',
            name='nl4_pair_2',
            field=models.CharField(blank=True, help_text='NL4 connector pair 2 +/- assignment', max_length=50, null=True, verbose_name='2 +/-'),
        ),
    ]
