# Generated by Django 5.2.4 on 2025-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0030_remove_ampchannel_nl4_output_ampchannel_nl4_pair_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampchannel',
            name='cacom_output',
        ),
        migrations.AddField(
            model_name='ampchannel',
            name='cacom_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cacom 1'),
        ),
        migrations.AddField(
            model_name='ampchannel',
            name='cacom_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cacom 2'),
        ),
        migrations.AddField(
            model_name='ampchannel',
            name='cacom_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cacom 3'),
        ),
        migrations.AddField(
            model_name='ampchannel',
            name='cacom_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cacom 4'),
        ),
    ]
