# Generated by Django 5.2.4 on 2025-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0031_remove_ampchannel_cacom_output_ampchannel_cacom_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampchannel',
            name='cacom_1',
        ),
        migrations.RemoveField(
            model_name='ampchannel',
            name='cacom_2',
        ),
        migrations.RemoveField(
            model_name='ampchannel',
            name='cacom_3',
        ),
        migrations.RemoveField(
            model_name='ampchannel',
            name='cacom_4',
        ),
        migrations.AddField(
            model_name='ampchannel',
            name='cacom_pair',
            field=models.CharField(blank=True, help_text='Which CA-COM pair (1-8) this channel routes to', max_length=50, null=True, verbose_name='CA-COM Pair'),
        ),
    ]
