# Generated by Django 5.2.4 on 2025-08-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0032_remove_ampchannel_cacom_1_remove_ampchannel_cacom_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amp',
            old_name='avb_stream_input',
            new_name='avb_stream',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='aes_input_count',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='analogue_input_count',
        ),
        migrations.AddField(
            model_name='amp',
            name='aes_input',
            field=models.CharField(blank=True, help_text='AES input source', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='amp',
            name='analogue_input',
            field=models.CharField(blank=True, help_text='Analogue input source', max_length=50, null=True),
        ),
    ]
