# Generated by Django 5.2.4 on 2025-08-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0033_rename_avb_stream_input_amp_avb_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amp',
            name='xlr_input_count',
        ),
        migrations.AlterField(
            model_name='amp',
            name='aes_input',
            field=models.CharField(blank=True, help_text='AES input source', max_length=50, null=True, verbose_name='AES Input'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='analogue_input',
            field=models.CharField(blank=True, help_text='Analogue input source', max_length=50, null=True, verbose_name='Analogue Input'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='avb_stream',
            field=models.CharField(blank=True, help_text='AVB stream source', max_length=50, null=True, verbose_name='AVB Stream'),
        ),
    ]
