# Generated by Django 5.2.4 on 2025-08-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0034_remove_amp_xlr_input_count_alter_amp_aes_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amp',
            name='aes_input',
            field=models.ForeignKey(blank=True, help_text='AES input source device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amps_using_as_aes', to='planner.device', verbose_name='AES Input'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='analogue_input',
            field=models.ForeignKey(blank=True, help_text='Analogue input source device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amps_using_as_analogue', to='planner.device', verbose_name='Analogue Input'),
        ),
    ]
