# Generated by Django 5.2.4 on 2025-08-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_alter_amp_aes_input_alter_amp_analogue_input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'I/O Device', 'verbose_name_plural': 'I/O Devices'},
        ),
        migrations.AlterModelOptions(
            name='deviceinput',
            options={'verbose_name': 'I/O Device Input', 'verbose_name_plural': 'I/O Device Inputs'},
        ),
        migrations.AlterModelOptions(
            name='deviceoutput',
            options={'verbose_name': 'I/O Device Input', 'verbose_name_plural': 'I/O Device Inputs'},
        ),
    ]
