# Generated by Django 5.2.4 on 2025-08-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0036_alter_device_options_alter_deviceinput_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDriveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device name/identifier', max_length=200)),
                ('device_type', models.CharField(choices=[('P1', "L'Acoustics P1"), ('GALAXY', 'Meyer GALAXY')], help_text='Type of system drive device', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Network IP address', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(help_text='Physical location of device', on_delete=django.db.models.deletion.CASCADE, related_name='system_drives', to='planner.location')),
            ],
            options={
                'verbose_name': 'System Drive Device',
                'verbose_name_plural': 'System Drive Devices',
            },
        ),
    ]
