# Generated by Django 5.2.4 on 2025-08-05 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0038_systemprocessor_delete_systemdrivedevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='P1Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Additional configuration notes', null=True)),
                ('system_processor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p1_config', to='planner.systemprocessor')),
            ],
            options={
                'verbose_name': 'P1 Processor',
                'verbose_name_plural': 'P1 Processors',
            },
        ),
        migrations.CreateModel(
            name='P1Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('ANALOG', 'Analog'), ('AES', 'AES/EBU'), ('AVB', 'AVB')], max_length=10)),
                ('channel_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text='Channel label/name', max_length=100, null=True)),
                ('assigned_bus', models.IntegerField(blank=True, choices=[(1, 'Bus 1'), (2, 'Bus 2'), (3, 'Bus 3'), (4, 'Bus 4'), (5, 'Bus 5'), (6, 'Bus 6'), (7, 'Bus 7'), (8, 'Bus 8')], help_text='Assigned bus (1-8)', null=True)),
                ('p1_processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='planner.p1processor')),
            ],
            options={
                'verbose_name': 'P1 Output',
                'verbose_name_plural': 'P1 Outputs',
                'ordering': ['output_type', 'channel_number'],
                'unique_together': {('p1_processor', 'output_type', 'channel_number')},
            },
        ),
        migrations.CreateModel(
            name='P1Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('ANALOG', 'Analog'), ('AES', 'AES/EBU'), ('AVB', 'AVB')], max_length=10)),
                ('channel_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text='Channel label/name', max_length=100, null=True)),
                ('origin_device_output', models.ForeignKey(blank=True, help_text='Source device output (for Analog/AES only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_inputs', to='planner.deviceoutput')),
                ('p1_processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='planner.p1processor')),
            ],
            options={
                'verbose_name': 'P1 Input',
                'verbose_name_plural': 'P1 Inputs',
                'ordering': ['input_type', 'channel_number'],
                'unique_together': {('p1_processor', 'input_type', 'channel_number')},
            },
        ),
    ]
