# Generated by Django 5.2.4 on 2025-08-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0039_p1processor_p1output_p1input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceoutput',
            options={'verbose_name': 'I/O Device Output', 'verbose_name_plural': 'I/O Device Outputs'},
        ),
    ]
