# Generated by Django 5.2.4 on 2025-08-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0040_alter_deviceoutput_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalaxyProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Configuration notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_processor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='galaxy_config', to='planner.systemprocessor')),
            ],
            options={
                'verbose_name': 'GALAXY Processor',
                'verbose_name_plural': 'GALAXY Processors',
            },
        ),
        migrations.CreateModel(
            name='GalaxyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('ANALOG', 'Analog'), ('AES', 'AES/EBU'), ('AVB', 'AVB/Milan')], max_length=10)),
                ('channel_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text='Channel label', max_length=100)),
                ('assigned_bus', models.PositiveIntegerField(blank=True, help_text='Assigned bus number', null=True)),
                ('destination', models.CharField(blank=True, help_text='Output destination (e.g., amp name, speaker zone)', max_length=100)),
                ('galaxy_processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='planner.galaxyprocessor')),
            ],
            options={
                'verbose_name': 'GALAXY Output',
                'verbose_name_plural': 'GALAXY Outputs',
                'ordering': ['output_type', 'channel_number'],
                'unique_together': {('galaxy_processor', 'output_type', 'channel_number')},
            },
        ),
        migrations.CreateModel(
            name='GalaxyInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('ANALOG', 'Analog'), ('AES', 'AES/EBU'), ('AVB', 'AVB/Milan')], max_length=10)),
                ('channel_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text='Channel label', max_length=100)),
                ('origin_device_output', models.ForeignKey(blank=True, help_text='Source device output for this input', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galaxy_inputs', to='planner.deviceoutput')),
                ('galaxy_processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='planner.galaxyprocessor')),
            ],
            options={
                'verbose_name': 'GALAXY Input',
                'verbose_name_plural': 'GALAXY Inputs',
                'ordering': ['input_type', 'channel_number'],
                'unique_together': {('galaxy_processor', 'input_type', 'channel_number')},
            },
        ),
    ]
