# Generated by Django 5.2.4 on 2025-08-23 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('planner', '0041_galaxyprocessor_galaxyoutput_galaxyinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceoutput',
            name='console_output',
        ),
        migrations.AddField(
            model_name='deviceoutput',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('consoleauxoutput', 'consolematrixoutput')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='deviceoutput',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
