# Generated by Django 5.2.4 on 2025-08-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0042_remove_deviceoutput_console_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('MAIN_L', 'Main Left'), ('MAIN_R', 'Main Right'), ('MAIN_C', 'Main Center'), ('SUB_L', 'Sub Left'), ('SUB_R', 'Sub Right'), ('SUB_C', 'Sub Center'), ('FRONT_FILL', 'Front Fill'), ('OUT_FILL_L', 'Out Fill Left'), ('OUT_FILL_R', 'Out Fill Right'), ('DELAY_1', 'Delay 1'), ('DELAY_2', 'Delay 2'), ('DELAY_3', 'Delay 3'), ('LIP_FILL', 'Lip Fill'), ('UNDER_BALC', 'Under Balcony'), ('BALCONY', 'Balcony')], max_length=20)),
                ('cable_type', models.CharField(choices=[('NL4_12AWG', 'NL4 - 12 AWG'), ('NL4_10AWG', 'NL4 - 10 AWG'), ('NL4_8AWG', 'NL4 - 8 AWG'), ('NL8_12AWG', 'NL8 - 12 AWG'), ('NL8_10AWG', 'NL8 - 10 AWG'), ('CA-COM', 'CA-COM'), ('AES_XLR', 'AES/EBU XLR'), ('ANALOG_XLR', 'Analog XLR'), ('CAT5E', 'Cat5e (Control)'), ('FIBER', 'Fiber Optic'), ('L14-30', 'L14-30 Power'), ('L21-30', 'L21-30 Power')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of cable runs')),
                ('length_per_run', models.DecimalField(decimal_places=1, help_text='Length in feet per run', max_digits=6)),
                ('service_loop', models.DecimalField(decimal_places=1, default=10.0, help_text='Extra length in feet for service loop', max_digits=4)),
                ('from_location', models.CharField(default='AMP RACK', help_text="Source location (e.g., 'SR AMP RACK 1')", max_length=50)),
                ('to_location', models.CharField(help_text="Destination (e.g., 'MAIN L TOP')", max_length=50)),
                ('drawing_ref', models.CharField(blank=True, help_text='VWX drawing dimension reference', max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amp_location', models.ForeignKey(blank=True, help_text='Amp location (for future automation)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.location')),
            ],
            options={
                'verbose_name': 'PA Cable Entry',
                'verbose_name_plural': 'PA Cable Entries',
                'ordering': ['zone', 'cable_type'],
            },
        ),
    ]
