# Generated by Django 5.2.4 on 2025-08-24 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0043_pacableschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacableschedule',
            options={'ordering': ['label__sort_order', 'label__name', 'cable'], 'verbose_name': 'PA Cable Entry', 'verbose_name_plural': 'PA Cable Entries'},
        ),
        migrations.AddField(
            model_name='pacableschedule',
            name='cable',
            field=models.CharField(choices=[('NL4_JUMPER', 'NL4 Jumper'), ('150_NL4', "150' NL4"), ('100_NL4', "100' NL4"), ('75_NL4', "75' NL4"), ('50_NL4', "50' NL4"), ('25_NL4', "25' NL4"), ('15_NL4', "15' NL4"), ('10_NL4', "10' NL4"), ('5_NL4', "5' NL4"), ('150_NL8', "150' NL8"), ('100_NL8', "100' NL8"), ('50_NL8', "50' NL8"), ('25_NL8', "25' NL8"), ('CA-COM', 'CA-COM'), ('AES_XLR', 'AES/EBU XLR'), ('L14-30', 'L14-30 Power')], default='100_NL4', max_length=20, verbose_name='Cable'),
        ),
        migrations.AddField(
            model_name='pacableschedule',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Number of cable runs', verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='pacableschedule',
            name='count2',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Additional count (for fan outs)', verbose_name='Count 2'),
        ),
        migrations.AddField(
            model_name='pacableschedule',
            name='destination',
            field=models.CharField(default='', help_text="e.g., 'KIVA - 1', 'K2 - Top'", max_length=50, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='pacableschedule',
            name='fan_out',
            field=models.CharField(blank=True, choices=[('', 'None'), ('NL4_Y', 'NL4 Y'), ('NL4_COUPLER', 'NL4 Coupler'), ('NL4_THRU', 'NL4 Thru'), ('NL8_Y', 'NL8 Y'), ('NL8_COUPLER', 'NL8 Coupler'), ('NL4_TO_NL8', 'NL4 to NL8'), ('NL8_TO_NL4', 'NL8 to NL4'), ('CACOM_SPLIT', 'CA-COM Split')], default='', max_length=20, verbose_name='Fan Out'),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='amp_location',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.location'),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='cable_type',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='drawing_ref',
            field=models.CharField(blank=True, help_text='VWX drawing dimension reference', max_length=50, null=True, verbose_name='Drawing Ref'),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='from_location',
            field=models.CharField(default='AMP RACK', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='length_per_run',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='notes',
            field=models.CharField(blank=True, help_text="e.g., 'Clr. 1 Top 2'", max_length=200, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='quantity',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='service_loop',
            field=models.DecimalField(decimal_places=1, default=10.0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='to_location',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='zone',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PAZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short zone code (e.g., HL, HR, FF1)', max_length=20, unique=True)),
                ('description', models.CharField(help_text='Full description (e.g., House Left, Front Fill 1)', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Order in dropdown (lower numbers appear first)')),
                ('zone_type', models.CharField(choices=[('MAIN', 'Main Array'), ('SUB', 'Subwoofer'), ('FILL', 'Fill'), ('DELAY', 'Delay'), ('MONITOR', 'Monitor'), ('CUSTOM', 'Custom')], default='CUSTOM', help_text='Category of zone', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pa_zones', to='planner.location')),
            ],
            options={
                'verbose_name': 'PA Zone',
                'verbose_name_plural': 'PA Zones',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pacableschedule',
            name='label',
            field=models.ForeignKey(blank=True, help_text='Zone label', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cables', to='planner.pazone', verbose_name='Label'),
        ),
    ]
