# Generated by Django 5.2.4 on 2025-09-08 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0044_alter_pacableschedule_options_pacableschedule_cable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacableschedule',
            name='count2',
        ),
        migrations.RemoveField(
            model_name='pacableschedule',
            name='fan_out',
        ),
        migrations.CreateModel(
            name='PAFanOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_out_type', models.CharField(blank=True, choices=[('', 'None'), ('NL4_Y', 'NL4 Y'), ('NL4_COUPLER', 'NL4 Coupler'), ('NL4_THRU', 'NL4 Thru'), ('NL8_Y', 'NL8 Y'), ('NL8_COUPLER', 'NL8 Coupler'), ('NL4_TO_NL8', 'NL4 to NL8'), ('NL8_TO_NL4', 'NL8 to NL4'), ('CACOM_SPLIT', 'CA-COM Split')], max_length=20)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cable_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_outs', to='planner.pacableschedule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
