# Generated by Django 5.2.4 on 2025-09-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0045_remove_pacableschedule_count2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pafanout',
            name='fan_out_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('NL4_Y', 'NL4 Y'), ('NL4_COUPLER', 'NL4 Coupler'), ('DOFILL', 'DOFill'), ('DOSUB', 'DOSub'), ('CACOM COUPLER', 'CACOM Coupler'), ('NL8_Y', 'NL8 Y'), ('NL8_COUPLER', 'NL8 Coupler'), ('NL4_TO_NL8', 'NL4 to NL8')], max_length=20),
        ),
    ]
