# Generated by Django 5.2.4 on 2025-09-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0046_alter_pafanout_fan_out_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacableschedule',
            name='length',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Cable length per run in feet', max_digits=6, verbose_name='Length (ft)'),
        ),
    ]
