# Generated by Django 5.2.4 on 2025-09-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0047_pacableschedule_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacableschedule',
            name='length',
            field=models.IntegerField(default=0, help_text='Cable length per run in feet', verbose_name='Length (ft)'),
        ),
    ]
