# Generated by Django 5.2.4 on 2025-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0050_alter_ampchannel_avb_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampchannel',
            name='nl4_pair_1',
        ),
        migrations.RemoveField(
            model_name='ampchannel',
            name='nl4_pair_2',
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_pair_1_minus',
            field=models.CharField(blank=True, help_text='NL4 Pin 1-', max_length=50, verbose_name='1-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_pair_1_plus',
            field=models.CharField(blank=True, help_text='NL4 Pin 1+', max_length=50, verbose_name='1+'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_pair_2_minus',
            field=models.CharField(blank=True, help_text='NL4 Pin 2-', max_length=50, verbose_name='2-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_pair_2_plus',
            field=models.CharField(blank=True, help_text='NL4 Pin 2+', max_length=50, verbose_name='2+'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_pair_3_minus',
            field=models.CharField(blank=True, help_text='NL4 Pin 3-', max_length=50, verbose_name='3-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_pair_3_plus',
            field=models.CharField(blank=True, help_text='NL4 Pin 3+', max_length=50, verbose_name='3+'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_pair_4_minus',
            field=models.CharField(blank=True, help_text='NL4 Pin 4-', max_length=50, verbose_name='4-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_pair_4_plus',
            field=models.CharField(blank=True, help_text='NL4 Pin 4+', max_length=50, verbose_name='4+'),
        ),
    ]
