# Generated by Django 5.2.4 on 2025-09-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0051_remove_ampchannel_nl4_pair_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amp',
            options={'ordering': ['location', 'ip_address', 'name'], 'verbose_name': 'Amplifier', 'verbose_name_plural': 'Amplifiers'},
        ),
        migrations.AlterUniqueTogether(
            name='amp',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ampchannel',
            name='analogue_input',
        ),
        migrations.RemoveField(
            model_name='ampchannel',
            name='cacom_pair',
        ),
        migrations.RemoveField(
            model_name='ampchannel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ampchannel',
            name='notes',
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_1_assignment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cacom 1'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_2_assignment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cacom 2'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_3_assignment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cacom 3'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_4_assignment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cacom 4'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_a_pair_1',
            field=models.CharField(blank=True, help_text="e.g., 'Ch1/Ch2' or 'Left/Right'", max_length=50, verbose_name='NL4-A Pair 1 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_a_pair_2',
            field=models.CharField(blank=True, help_text="e.g., 'Ch3/Ch4' or 'Sub L/Sub R'", max_length=50, verbose_name='NL4-A Pair 2 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_b_pair_1',
            field=models.CharField(blank=True, help_text="e.g., 'Ch5/Ch6'", max_length=50, verbose_name='NL4-B Pair 1 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl4_b_pair_2',
            field=models.CharField(blank=True, help_text="e.g., 'Ch7/Ch8'", max_length=50, verbose_name='NL4-B Pair 2 +/-'),
        ),
        migrations.AddField(
            model_name='ampchannel',
            name='analog_input',
            field=models.CharField(blank=True, help_text='Analog input assignment', max_length=50, verbose_name='Analog Input'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amp',
            name='name',
            field=models.CharField(help_text="Unique identifier (e.g., 'LA12X-1', 'Stage Left 1')", max_length=100),
        ),
        migrations.AlterField(
            model_name='ampchannel',
            name='aes_input',
            field=models.CharField(blank=True, default='', help_text='AES input assignment', max_length=50, verbose_name='AES Input'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ampchannel',
            name='avb_stream',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'AVB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amp_channels', to='planner.p1output', verbose_name='AVB Stream'),
        ),
        migrations.AlterField(
            model_name='ampchannel',
            name='channel_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ampchannel',
            name='channel_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='AmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('channel_count', models.IntegerField()),
                ('has_analog_inputs', models.BooleanField(default=True)),
                ('has_aes_inputs', models.BooleanField(default=False)),
                ('has_avb_inputs', models.BooleanField(default=False)),
                ('nl4_connector_count', models.IntegerField(choices=[(0, 'None'), (1, '1 NL4'), (2, '2 NL4')], default=0)),
                ('cacom_output_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Amplifier Model',
                'verbose_name_plural': 'Amplifier Models',
                'ordering': ['manufacturer', 'model_name'],
                'unique_together': {('manufacturer', 'model_name')},
            },
        ),
        migrations.AddField(
            model_name='amp',
            name='amp_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.ampmodel'),
        ),
        migrations.RemoveField(
            model_name='amp',
            name='aes_input',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='analogue_input',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='avb_stream',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='cacom_output',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='channel_count',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='nl4_pair_1_minus',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='nl4_pair_1_plus',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='nl4_pair_2_minus',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='nl4_pair_2_plus',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='nl4_pair_3_minus',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='nl4_pair_3_plus',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='nl4_pair_4_minus',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='nl4_pair_4_plus',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='preset_name',
        ),
    ]
