# Generated by Django 5.2.4 on 2025-09-13 23:00

from django.db import migrations

def create_amp_models(apps, schema_editor):
    # SKIP in production if no projects exist yet
    Project = apps.get_model('planner', 'Project')
    if not Project.objects.exists():
        return  # Skip this migration

    AmpModel = apps.get_model('planner', 'AmpModel')
    
    amp_models = [
        # L-Acoustics Amplifiers
        {
            'manufacturer': 'L-Acoustics', 
            'model_name': 'LA12X', 
            'channel_count': 4,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': True,
            'nl4_connector_count': 2,  # Has 2 NL4 connectors
            'cacom_output_count': 4     # Has 4 Cacom outputs
        },
        {
            'manufacturer': 'L-Acoustics', 
            'model_name': 'LA8', 
            'channel_count': 4,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': False,  # No AVB on LA8
            'nl4_connector_count': 2,
            'cacom_output_count': 4
        },
        {
            'manufacturer': 'L-Acoustics', 
            'model_name': 'LA4X', 
            'channel_count': 4,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': True,
            'nl4_connector_count': 1,  # Only 1 NL4 connector
            'cacom_output_count': 4
        },
        {
            'manufacturer': 'L-Acoustics', 
            'model_name': 'LA2Xi', 
            'channel_count': 4,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': True,
            'nl4_connector_count': 1,
            'cacom_output_count': 4
        },
        
        # Powersoft Amplifiers
        {
            'manufacturer': 'Powersoft', 
            'model_name': 'X4', 
            'channel_count': 4,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': False,
            'nl4_connector_count': 2,
            'cacom_output_count': 0  # No Cacom outputs
        },
        {
            'manufacturer': 'Powersoft', 
            'model_name': 'X8', 
            'channel_count': 8,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': False,
            'nl4_connector_count': 2,
            'cacom_output_count': 0
        },
        {
            'manufacturer': 'Powersoft', 
            'model_name': 'K10', 
            'channel_count': 2,
            'has_analog_inputs': True, 
            'has_aes_inputs': False, 
            'has_avb_inputs': False,
            'nl4_connector_count': 1,
            'cacom_output_count': 0
        },
        
        # Meyer Sound Amplifiers
        {
            'manufacturer': 'Meyer Sound', 
            'model_name': 'Galileo GALAXY 816', 
            'channel_count': 16,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': True,
            'nl4_connector_count': 0,  # Uses different connectors
            'cacom_output_count': 0
        },
        
        # d&b Amplifiers
        {
            'manufacturer': 'd&b audiotechnik', 
            'model_name': 'D80', 
            'channel_count': 4,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': False,
            'nl4_connector_count': 2,
            'cacom_output_count': 0
        },
        {
            'manufacturer': 'd&b audiotechnik', 
            'model_name': 'D20', 
            'channel_count': 4,
            'has_analog_inputs': True, 
            'has_aes_inputs': True, 
            'has_avb_inputs': False,
            'nl4_connector_count': 2,
            'cacom_output_count': 0
        },
    ]
    
    for model_data in amp_models:
        AmpModel.objects.create(**model_data)

def reverse_amp_models(apps, schema_editor):
    AmpModel = apps.get_model('planner', 'AmpModel')
    AmpModel.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
    ('planner', '0052_alter_amp_options_alter_amp_unique_together_and_more'),  # Use your actual previous migration
]
    
    operations = [
        migrations.RunPython(create_amp_models, reverse_amp_models),
    ]