# Generated by Django 5.2.4 on 2025-09-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0053_populate_amp_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampchannel',
            name='avb_stream',
            field=models.ForeignKey(blank=True, limit_choices_to={'output_type': 'AVB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amp_channels', to='planner.p1output', verbose_name='AVB Stream'),
        ),
    ]
