# Generated by Django 5.2.4 on 2025-09-14 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0054_alter_ampchannel_avb_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_designation', models.CharField(help_text="e.g., '1 4W', '2 4W', 'A 2W', 'B 2W'", max_length=10)),
                ('channel_type', models.CharField(choices=[('4W', '4-Wire'), ('2W', '2-Wire')], max_length=2)),
                ('channel_number', models.CharField(help_text="e.g., 'FS II - 1'", max_length=20)),
                ('name', models.CharField(help_text="Full channel name (e.g., 'Production', 'Audio')", max_length=50)),
                ('abbreviation', models.CharField(help_text="Short name (e.g., 'PROD', 'AUDIO')", max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Comm Channel',
                'verbose_name_plural': 'Comm Channels',
                'ordering': ['order', 'channel_number'],
            },
        ),
        migrations.CreateModel(
            name='CommCrewName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Comm Crew Name',
                'verbose_name_plural': 'Comm Crew Names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Comm Position',
                'verbose_name_plural': 'Comm Positions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommBeltPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_number', models.IntegerField(unique=True, verbose_name='BP #')),
                ('position', models.CharField(blank=True, help_text='Select from dropdown or enter custom', max_length=100)),
                ('name', models.CharField(blank=True, help_text='Crew member name', max_length=100)),
                ('headset', models.CharField(blank=True, choices=[('SM', 'Single Muff'), ('DM', 'Double Muff'), ('IE', 'In-Ear'), ('SS', 'Speaker Station'), ('HM', 'Handmic'), ('', 'None')], max_length=2, verbose_name='Headset Type')),
                ('audio_pgm', models.BooleanField(default=False, help_text='Receives audio program feed', verbose_name='AUDIO PGM')),
                ('group', models.CharField(blank=True, choices=[('PROD', 'Production'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('LIGHTS', 'Lighting'), ('STAGE', 'Stage'), ('', 'None')], help_text='Department/Group assignment', max_length=10)),
                ('checked_out', models.BooleanField(default=False, verbose_name='Checked Out')),
                ('notes', models.TextField(blank=True)),
                ('channel_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpack_channel_a', to='planner.commchannel', verbose_name='CH A')),
                ('channel_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpack_channel_b', to='planner.commchannel', verbose_name='CH B')),
                ('channel_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpack_channel_c', to='planner.commchannel', verbose_name='CH C')),
                ('channel_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpack_channel_d', to='planner.commchannel', verbose_name='CH D')),
            ],
            options={
                'verbose_name': 'Comm Belt Pack',
                'verbose_name_plural': 'Comm Belt Packs',
                'ordering': ['bp_number'],
            },
        ),
    ]
