# Generated by Django 5.2.4 on 2025-09-14 20:42

from django.db import migrations

def populate_comm_defaults(apps, schema_editor):
    CommChannel = apps.get_model('planner', 'CommChannel')
    CommPosition = apps.get_model('planner', 'CommPosition')
    
    # Create default FS II channels
    default_channels = [
        ('1 4W', 'FS II - 1', 'Production', 'PROD', 1),
        ('2 4W', 'FS II - 2', 'Audio', 'AUDIO', 2),
        ('3 4W', 'FS II - 3', 'Video', 'VIDEO', 3),
        ('4 4W', 'FS II - 4', 'Lights', 'LIGHTS', 4),
        ('A 2W', 'FS II - 5', 'Camera', 'CAMS', 5),
        ('B 2W', 'FS II - 6', 'Graphics', 'GFX', 6),
        ('C 2W', 'FS II - 7', 'Stage Mgr', 'SM', 7),
        ('D 2W', 'FS II - 8', 'Carps', 'CARP', 8),
        ('', 'FS II - 9', 'ALL', 'ALL', 9),
        ('', 'FS II - 10', 'Program', 'PGM', 10),
    ]
    
    for input_des, channel_num, name, abbr, order in default_channels:
        channel_type = '4W' if '4W' in input_des else '2W' if '2W' in input_des else ''
        CommChannel.objects.get_or_create(
            channel_number=channel_num,
            defaults={
                'input_designation': input_des,
                'channel_type': channel_type,
                'name': name,
                'abbreviation': abbr,
                'order': order
            }
        )
    
    # Create common positions
    positions = [
        ('FOH', 1),
        ('Monitor World', 2),
        ('Stage Left', 3),
        ('Stage Right', 4),
        ('Spot 1', 5),
        ('Spot 2', 6),
        ('Spot 3', 7),
        ('Spot 4', 8),
        ('Truck', 9),
        ('Backstage', 10),
        ('Catering', 11),
        ('Office', 12),
        ('Rigging', 13),
        ('Dimmer Beach', 14),
        ('Video World', 15),
        ('Patch', 16),
        ('Followspot Platform', 17),
        ('House Mix', 18),
        ('Stage Manager Desk', 19),
        ('Loading Dock', 20),
    ]
    
    for name, order in positions:
        CommPosition.objects.get_or_create(
            name=name,
            defaults={'order': order}
        )

def reverse_comm_defaults(apps, schema_editor):
    CommChannel = apps.get_model('planner', 'CommChannel')
    CommPosition = apps.get_model('planner', 'CommPosition')
    
    CommChannel.objects.all().delete()
    CommPosition.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('planner', '0055_commchannel_commcrewname_commposition_commbeltpack'),  
    ]
    
    operations = [
        migrations.RunPython(populate_comm_defaults, reverse_comm_defaults),
    ]