# Generated by Django 5.2.4 on 2025-09-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0056_populate_comm_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commbeltpack',
            options={'ordering': ['system_type', 'bp_number'], 'verbose_name': 'Comm Belt Pack', 'verbose_name_plural': 'Comm Belt Packs'},
        ),
        migrations.AddField(
            model_name='commbeltpack',
            name='system_type',
            field=models.CharField(choices=[('WIRELESS', 'Wireless'), ('HARDWIRED', 'Hardwired')], default='WIRELESS', max_length=10, verbose_name='System Type'),
        ),
        migrations.AddField(
            model_name='commbeltpack',
            name='unit_location',
            field=models.CharField(blank=True, help_text="Location of wireless unit (e.g., 'Unit #1 - FOH Rack')", max_length=100),
        ),
        migrations.AlterField(
            model_name='commbeltpack',
            name='bp_number',
            field=models.IntegerField(verbose_name='BP #'),
        ),
        migrations.AlterUniqueTogether(
            name='commbeltpack',
            unique_together={('system_type', 'bp_number')},
        ),
    ]
