# Generated by Django 5.2.4 on 2025-09-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0057_alter_commbeltpack_options_commbeltpack_system_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commbeltpack',
            name='checked_out',
            field=models.BooleanField(default=False, help_text='Whether this belt pack has been checked out (Wireless only)'),
        ),
    ]
