# Generated by Django 5.2.4 on 2025-09-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0058_alter_commbeltpack_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='commbeltpack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
