# Generated by Django 5.2.4 on 2025-09-18 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0059_commbeltpack_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicShowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(blank=True, max_length=200)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('ballroom_name', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('default_mics_per_session', models.IntegerField(default=16)),
                ('default_session_duration', models.IntegerField(default=60, help_text='Default session duration in minutes')),
            ],
            options={
                'verbose_name': 'Mic Show Information',
                'verbose_name_plural': 'Mic Show Information',
            },
        ),
        migrations.CreateModel(
            name='ShowDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, help_text="Optional name for the day (e.g., 'Day 1 - Setup')", max_length=100)),
                ('is_collapsed', models.BooleanField(default=False, help_text='UI state: whether this day is collapsed in the view')),
                ('order', models.IntegerField(default=0, help_text='Display order for days')),
            ],
            options={
                'verbose_name': 'Show Day',
                'verbose_name_plural': 'Show Days',
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('REHEARSAL', 'Rehearsal'), ('KEYNOTE', 'Keynote'), ('PANEL', 'Panel Discussion'), ('BREAKOUT', 'Breakout Session'), ('GENERAL', 'General Session'), ('TECH_CHECK', 'Tech Check'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('num_mics', models.IntegerField(default=16, help_text='Number of mics available for this session', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('column_position', models.IntegerField(default=0, help_text='Position in the display grid (0-2 for 3-column layout)')),
                ('order', models.IntegerField(default=0, help_text='Display order within the day')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planner.showday')),
            ],
            options={
                'verbose_name': 'Mic Session',
                'verbose_name_plural': 'Mic Sessions',
                'ordering': ['day', 'order', 'start_time'],
                'unique_together': {('day', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mic_type', models.CharField(blank=True, choices=[('', '---'), ('HH', 'Handheld'), ('LAV', 'Lavalier'), ('HEADSET', 'Headset'), ('PODIUM', 'Podium'), ('BOOM', 'Boom'), ('BOUNDARY', 'Boundary'), ('GOOSENECK', 'Gooseneck'), ('COMBO', 'Combo Pack')], max_length=20)),
                ('presenter_name', models.CharField(blank=True, max_length=200)),
                ('is_micd', models.BooleanField(default=False, verbose_name="MIC'D")),
                ('is_d_mic', models.BooleanField(default=False, verbose_name='D-MIC')),
                ('shared_presenters', models.JSONField(blank=True, help_text='List of additional presenters sharing this mic', null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mic_modifications', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mic_assignments', to='planner.micsession')),
            ],
            options={
                'verbose_name': 'Mic Assignment',
                'verbose_name_plural': 'Mic Assignments',
                'ordering': ['session', 'rf_number'],
                'unique_together': {('session', 'rf_number')},
            },
        ),
    ]
