# Generated by Django 5.2.4 on 2025-09-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0060_micshowinfo_showday_micsession_micassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micassignment',
            name='shared_presenters',
            field=models.JSONField(blank=True, default=list, help_text='List of additional presenters sharing this mic'),
        ),
    ]
