# Generated by Django 5.2.4 on 2025-09-21 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0061_alter_micassignment_shared_presenters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmplifierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('idle_power_watts', models.IntegerField(help_text='Idle/quiescent power draw in watts')),
                ('rated_power_watts', models.IntegerField(help_text='1/8 power (pink noise) in watts - typical operating power')),
                ('peak_power_watts', models.IntegerField(help_text='1/3 power (heavy program) in watts')),
                ('max_power_watts', models.IntegerField(help_text='Maximum rated power in watts')),
                ('nominal_voltage', models.IntegerField(choices=[(120, '120V'), (208, '208V'), (240, '240V')], default=208)),
                ('power_factor', models.DecimalField(decimal_places=2, default=0.95, help_text='Power factor (typically 0.95 for modern amps)', max_digits=3)),
                ('efficiency', models.DecimalField(decimal_places=2, default=0.9, help_text='Amplifier efficiency (typically 0.85-0.95)', max_digits=3)),
                ('channels', models.IntegerField(default=4)),
                ('rack_units', models.IntegerField(default=2)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
                'unique_together': {('manufacturer', 'model')},
            },
        ),
        migrations.CreateModel(
            name='PowerDistributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('3phase_4wire_208', '3-Phase 4-Wire 208V'), ('3phase_5wire_208', '3-Phase 5-Wire 208V'), ('3phase_4wire_240', '3-Phase 4-Wire 240V'), ('single_phase_120', 'Single Phase 120V'), ('single_phase_240', 'Single Phase 240V')], default='3phase_4wire_208', max_length=50)),
                ('available_amperage_per_leg', models.IntegerField(default=400, help_text='Total available amps per leg')),
                ('transient_headroom', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for transient peaks (1.5 = 50% headroom)', max_digits=3)),
                ('safety_margin', models.DecimalField(decimal_places=2, default=0.8, help_text='Derating factor (0.8 = use only 80% of available)', max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_plans_created', to=settings.AUTH_USER_MODEL)),
                ('show_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_plans', to='planner.showday')),
            ],
            options={
                'ordering': ['-show_day__date'],
            },
        ),
        migrations.CreateModel(
            name='AmplifierAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('zone', models.CharField(help_text='Location (e.g., FOH, Delays, Fills)', max_length=100)),
                ('position', models.CharField(blank=True, help_text='Specific position within zone', max_length=100)),
                ('phase_assignment', models.CharField(choices=[('L1', 'Phase L1/A'), ('L2', 'Phase L2/B'), ('L3', 'Phase L3/C'), ('AUTO', 'Auto-Balance')], default='AUTO', max_length=10)),
                ('duty_cycle', models.CharField(choices=[('speech', 'Speech/Vocal (20% duty)'), ('light_music', 'Light Music (35% duty)'), ('heavy_music', 'Heavy Music (50% duty)'), ('edm_concert', 'EDM/Concert (70% duty)'), ('test_tone', 'Test/Alignment (100% duty)')], default='heavy_music', max_length=50)),
                ('calculated_current_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated current draw per amplifier', max_digits=6, null=True)),
                ('calculated_total_current', models.DecimalField(blank=True, decimal_places=2, help_text='Total current draw for all units', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amplifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.amplifierprofile')),
                ('distribution_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amplifier_assignments', to='planner.powerdistributionplan')),
            ],
            options={
                'ordering': ['zone', 'position', 'amplifier'],
            },
        ),
    ]
