# Generated by Django 5.2.4 on 2025-09-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0062_amplifierprofile_powerdistributionplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Audio Checklist',
                'verbose_name_plural': 'Audio Checklists',
                'db_table': 'audio_checklist_dummy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoundvisionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('date_generated', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='predictions/')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('show_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='planner.showday')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('array_base_name', models.CharField(max_length=100)),
                ('symmetry_type', models.CharField(blank=True, max_length=50)),
                ('group_context', models.CharField(blank=True, max_length=50)),
                ('configuration', models.CharField(choices=[('vertical_flown', 'Vertical, Flown Array'), ('vertical_ground', 'Vertical, Ground Stack'), ('horizontal_flown', 'Horizontal, Flown Array'), ('horizontal_ground', 'Horizontal, Ground Stack')], max_length=50)),
                ('bumper_type', models.CharField(choices=[('KIBU-SB', 'KIBU-SB'), ('KIBU II', 'KIBU II'), ('M-BUMP', 'M-BUMP'), ('K1-BUMP', 'K1-BUMP'), ('K2-BUMP', 'K2-BUMP'), ('A-BUMP', 'A-BUMP'), ('NONE', 'No Bumper')], max_length=20)),
                ('position_x', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('position_y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('position_z', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('site_angle', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('azimuth', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('top_site', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('bottom_site', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('num_motors', models.IntegerField(default=1)),
                ('front_pickup_position', models.CharField(blank=True, max_length=100)),
                ('rear_pickup_position', models.CharField(blank=True, max_length=100)),
                ('front_motor_load_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rear_motor_load_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_weight_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('enclosure_weight_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bottom_elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('spatial_dimensions', models.CharField(blank=True, max_length=100)),
                ('mbar_hole', models.CharField(blank=True, max_length=10)),
                ('is_single_point', models.BooleanField(default=False)),
                ('bumper_angle', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_arrays', to='planner.soundvisionprediction')),
            ],
            options={
                'ordering': ['array_base_name', 'source_name'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.IntegerField()),
                ('speaker_model', models.CharField(choices=[('KIVA II', 'KIVA II'), ('KARA II', 'KARA II'), ('K1', 'K1'), ('K2', 'K2'), ('K3', 'K3'), ('A10', 'A10 (Focus/Wide)'), ('A15', 'A15 (Focus/Wide)'), ('ARCS', 'ARCS (Focus/Wide)'), ('SB15M', 'SB15M'), ('SB18', 'SB18'), ('SB28', 'SB28'), ('KS21', 'KS21'), ('KS28', 'KS28')], max_length=20)),
                ('angle_to_next', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('site_angle', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('top_z', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bottom_z', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('panflex_setting', models.CharField(blank=True, choices=[('55/55', '55°/55°'), ('55/35', '55°/35°'), ('35/55', '35°/55°'), ('35/35', '35°/35°'), ('70/70', '70°/70°'), ('110/110', '110°/110°'), ('FOCUS', 'Focus'), ('WIDE', 'Wide')], max_length=10)),
                ('array', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='planner.speakerarray')),
            ],
            options={
                'ordering': ['array', 'position_number'],
                'unique_together': {('array', 'position_number')},
            },
        ),
    ]
