# Generated by Django 5.0.9 on 2025-09-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0063_audiochecklist_soundvisionprediction_speakerarray_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amp',
            options={'ordering': ['ip_address'], 'verbose_name': 'Amplifier Assignment', 'verbose_name_plural': '⚡ Amplifier Assignments'},
        ),
        migrations.AlterModelOptions(
            name='ampchannel',
            options={'ordering': ['id'], 'verbose_name': 'Amp Channel', 'verbose_name_plural': '    ├─ Amp Channels'},
        ),
        migrations.AlterModelOptions(
            name='amplifierassignment',
            options={'ordering': ['id'], 'verbose_name': 'Amplifiers in Power Plan', 'verbose_name_plural': '⚡ Amplifiers in Power Plan'},
        ),
        migrations.AlterModelOptions(
            name='amplifierprofile',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Amplifier Profile', 'verbose_name_plural': '    • Amplifier Profiles'},
        ),
        migrations.AlterModelOptions(
            name='ampmodel',
            options={'ordering': ['id'], 'verbose_name': 'Amp Model Template', 'verbose_name_plural': '    • Amp Model Templates'},
        ),
        migrations.AlterModelOptions(
            name='commbeltpack',
            options={'ordering': ['bp_number'], 'verbose_name': 'Comm Belt Pack', 'verbose_name_plural': '📡 Comm Belt Packs'},
        ),
        migrations.AlterModelOptions(
            name='commchannel',
            options={'ordering': ['id'], 'verbose_name': 'Comm Channel', 'verbose_name_plural': '    • Comm Channels'},
        ),
        migrations.AlterModelOptions(
            name='commcrewname',
            options={'ordering': ['id'], 'verbose_name': 'Comm Position', 'verbose_name_plural': '    • Comm Positions'},
        ),
        migrations.AlterModelOptions(
            name='commposition',
            options={'ordering': ['name'], 'verbose_name': 'Comm Position', 'verbose_name_plural': '    • Comm Positions'},
        ),
        migrations.AlterModelOptions(
            name='console',
            options={'ordering': ['name'], 'verbose_name': 'Console', 'verbose_name_plural': '🎛️ Consoles'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'I/O Device', 'verbose_name_plural': '🎚️ I/O Devices'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': '    • Comm Locations'},
        ),
        migrations.AlterModelOptions(
            name='micassignment',
            options={'ordering': ['rf_number'], 'verbose_name': 'Mic Assignment', 'verbose_name_plural': '    • Mic Assignments'},
        ),
        migrations.AlterModelOptions(
            name='micsession',
            options={'ordering': ['day', 'order'], 'verbose_name': 'Mic Session', 'verbose_name_plural': '    • Mic Sessions'},
        ),
        migrations.AlterModelOptions(
            name='pacableschedule',
            options={'ordering': ['id'], 'verbose_name': 'PA Cable Entry', 'verbose_name_plural': '🔌 PA Cable Entries'},
        ),
        migrations.AlterModelOptions(
            name='pafanout',
            options={'ordering': ['id'], 'verbose_name': 'PA Fan Out', 'verbose_name_plural': '    └─ PA Fan Outs'},
        ),
        migrations.AlterModelOptions(
            name='pazone',
            options={'ordering': ['id'], 'verbose_name': 'PA Zone', 'verbose_name_plural': '    • PA Zones'},
        ),
        migrations.AlterModelOptions(
            name='powerdistributionplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Power Distribution Plan', 'verbose_name_plural': '⚡ Power Distribution Plans'},
        ),
        migrations.AlterModelOptions(
            name='showday',
            options={'ordering': ['date'], 'verbose_name': 'Show Day', 'verbose_name_plural': '📅 Show Days'},
        ),
        migrations.AlterModelOptions(
            name='soundvisionprediction',
            options={'verbose_name': 'Soundvision Prediction', 'verbose_name_plural': 'Soundvision Predictions'},
        ),
        migrations.AlterModelOptions(
            name='speakerarray',
            options={'ordering': ['prediction', 'array_base_name'], 'verbose_name': 'Speaker Array', 'verbose_name_plural': '    • Speaker Arrays'},
        ),
        migrations.AlterModelOptions(
            name='speakercabinet',
            options={'ordering': ['id'], 'verbose_name': 'Speaker Cabinet', 'verbose_name_plural': '    • Speaker Cabinets'},
        ),
        migrations.AlterModelOptions(
            name='systemprocessor',
            options={'ordering': ['name'], 'verbose_name': 'System Processor', 'verbose_name_plural': '🔊 System Processors'},
        ),
        migrations.AlterUniqueTogether(
            name='ampchannel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='amplifierprofile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ampmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='commbeltpack',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='micassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='micsession',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='speakercabinet',
            unique_together=set(),
        ),
    ]
