# Generated by Django 5.0.9 on 2025-09-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0066_alter_amp_options_alter_amplifierassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amp',
            options={'ordering': ['ip_address'], 'verbose_name': 'Amplifier Assignment', 'verbose_name_plural': '    └─ Amplifier Assignments'},
        ),
        migrations.AlterModelOptions(
            name='ampmodel',
            options={'ordering': ['id'], 'verbose_name': 'Amp Model Template', 'verbose_name_plural': '    ├─ Amp Model Templates'},
        ),
        migrations.AlterModelOptions(
            name='commcrewname',
            options={'ordering': ['id'], 'verbose_name': 'Comm Position', 'verbose_name_plural': '    ├─ Comm Positions'},
        ),
        migrations.AlterModelOptions(
            name='commposition',
            options={'ordering': ['name'], 'verbose_name': 'Comm Position', 'verbose_name_plural': '    ├─ Comm Positions'},
        ),
    ]
