# Generated by Django 5.0.9 on 2025-10-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0067_alter_amp_options_alter_ampmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commcrewname',
            options={'ordering': ['id'], 'verbose_name': 'Comm Crew Name', 'verbose_name_plural': '    ├─ Comm Crew Names'},
        ),
        migrations.AddField(
            model_name='consoleauxoutput',
            name='dante_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolematrixoutput',
            name='dante_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
