# Generated by Django 5.0.9 on 2025-10-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0068_alter_commcrewname_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleStereoOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stereo_type', models.CharField(choices=[('AL', 'Stereo A - Left'), ('AR', 'Stereo A - Right'), ('BL', 'Stereo B - Left'), ('BR', 'Stereo B - Right')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dante_number', models.IntegerField(blank=True, null=True)),
                ('omni_out', models.CharField(blank=True, max_length=100, null=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.console')),
            ],
            options={
                'ordering': ['stereo_type'],
            },
        ),
    ]
