# Generated by Django 5.0.9 on 2025-10-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0069_consolestereooutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolestereooutput',
            name='stereo_type',
            field=models.CharField(choices=[('L', 'Stereo Left'), ('R', 'Stereo Right'), ('M', 'Mono')], max_length=2, verbose_name='Buss'),
        ),
    ]
