# Generated by Django 5.0.9 on 2025-10-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0070_alter_consolestereooutput_stereo_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='console',
            options={'ordering': ['-is_template', 'name'], 'verbose_name': 'Console', 'verbose_name_plural': 'Consoles'},
        ),
        migrations.AddField(
            model_name='console',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Mark this console as a template for creating new consoles'),
        ),
    ]
