# Generated by Django 5.0.9 on 2025-10-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0071_alter_console_options_console_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='micassignment',
            name='active_presenter_index',
            field=models.IntegerField(default=0),
        ),
    ]
