# Generated by Django 5.0.9 on 2025-10-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0072_micassignment_active_presenter_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amp',
            options={'ordering': ['ip_address'], 'verbose_name': 'Amplifier Assignment', 'verbose_name_plural': 'Amplifier Assignments'},
        ),
        migrations.AlterModelOptions(
            name='ampmodel',
            options={'ordering': ['id'], 'verbose_name': 'Amp Model Template', 'verbose_name_plural': '    └─ Amp Model Templates'},
        ),
    ]
