# Generated by Django 5.0.9 on 2025-10-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0073_alter_amp_options_alter_ampmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': '    ├─ Locations'},
        ),
    ]
