# Generated by Django 5.0.9 on 2025-10-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0074_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': '    └─ Locations'},
        ),
    ]
