# Generated by Django 5.0.9 on 2025-10-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0075_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showday',
            options={'ordering': ['date'], 'verbose_name': 'Show Mic Tracker', 'verbose_name_plural': 'Show Mic Tracker'},
        ),
    ]
