# Generated by Django 5.0.9 on 2025-10-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0076_alter_showday_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoleinput',
            name='omni_out',
        ),
    ]
