# Generated by Django 5.0.9 on 2025-10-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0077_remove_consoleinput_omni_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of presenter', max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this presenter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Presenter',
                'verbose_name_plural': 'Presenters',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='amp',
            name='cacom_1_assignment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ch 1'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='cacom_2_assignment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ch 2'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='cacom_3_assignment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ch 3'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='cacom_4_assignment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ch 4'),
        ),
    ]
