# Generated by Django 5.0.9 on 2025-10-21 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0078_add_presenter_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micassignment',
            name='presenter_name',
        ),
        migrations.AddField(
            model_name='micassignment',
            name='presenter',
            field=models.ForeignKey(blank=True, help_text='Primary presenter for this mic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mic_assignments', to='planner.presenter'),
        ),
        migrations.RemoveField(
            model_name='micassignment',
            name='shared_presenters',
        ),
        migrations.AddField(
            model_name='micassignment',
            name='shared_presenters',
            field=models.ManyToManyField(blank=True, help_text='Additional presenters sharing this mic', related_name='shared_mic_assignments', to='planner.presenter'),
        ),
    ]
