# Generated by Django 5.0.9 on 2025-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0079_add_presenter_and_update_mic_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenter',
            options={'ordering': ['name'], 'verbose_name': 'Presenter', 'verbose_name_plural': '  ├─ Presenters'},
        ),
        migrations.AddField(
            model_name='console',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Console IP address (optional)', null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
