# Generated by Django 5.0.9 on 2025-10-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0080_alter_presenter_options_console_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Device IP address (optional)', null=True, verbose_name='IP Address'),
        ),
    ]
