# Generated by Django 5.0.9 on 2025-10-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0081_device_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='console',
            name='primary_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Primary console IP address (optional)', null=True, verbose_name='Primary IP Address'),
        ),
        migrations.AddField(
            model_name='console',
            name='secondary_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Secondary console IP address (optional)', null=True, verbose_name='Secondary IP Address'),
        ),
        migrations.AddField(
            model_name='device',
            name='primary_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Primary device IP address (optional)', null=True, verbose_name='Primary IP Address'),
        ),
        migrations.AddField(
            model_name='device',
            name='secondary_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Secondary device IP address (optional)', null=True, verbose_name='Secondary IP Address'),
        ),
    ]
