# Generated by Django 5.0.9 on 2025-10-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0082_remove_console_ip_address_remove_device_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commbeltpack',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address for hardwired belt packs (optional)', null=True, verbose_name='IP Address'),
        ),
    ]
