# Generated by Django 5.2.4 on 2025-10-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0084_project_amp_project_commbeltpack_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name_plural': 'Equip Locations'},
        ),
    ]
