# Generated by Django 5.2.4 on 2025-10-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0085_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consoles', to='planner.location'),
        ),
    ]
