# Generated by Django 5.2.4 on 2025-11-01 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0088_alter_projectmember_invited_by_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commcrewname',
            name='project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='planner.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commposition',
            name='project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='planner.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_invite', to=settings.AUTH_USER_MODEL),
        ),
    ]
