# Generated by Django 5.2.4 on 2025-11-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0089_commcrewname_project_commposition_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commchannel',
            name='project',
            field=models.ForeignKey(default=3, help_text='Project this channel belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comm_channels', to='planner.project'),
            preserve_default=False,
        ),
    ]
