# Generated by Django 5.2.4 on 2025-11-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0090_commchannel_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='project',
            field=models.ForeignKey(default=3, help_text='Project this presenter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='presenters', to='planner.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presenter',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
