# Generated by Django 5.2.4 on 2025-11-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0091_presenter_project_alter_presenter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='micshowinfo',
            name='project',
            field=models.OneToOneField(default=3, help_text='Project this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mic_show_info', to='planner.project'),
            preserve_default=False,
        ),
    ]
