# Generated by Django 5.2.4 on 2025-11-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0092_micshowinfo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commbeltpack',
            name='name',
            field=models.ForeignKey(blank=True, help_text='Crew member name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpacks', to='planner.commcrewname'),
        ),
        migrations.AlterField(
            model_name='commbeltpack',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Position assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpacks', to='planner.commposition'),
        ),
    ]
