# Generated by Django 5.2.4 on 2025-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0093_alter_commbeltpack_name_alter_commbeltpack_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='amp',
            name='nl8_a_pair_1',
            field=models.CharField(blank=True, help_text="e.g., 'Ch1/Ch2'", max_length=50, verbose_name='NL8-A Pair 1 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl8_a_pair_2',
            field=models.CharField(blank=True, help_text="e.g., 'Ch3/Ch4'", max_length=50, verbose_name='NL8-A Pair 2 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl8_a_pair_3',
            field=models.CharField(blank=True, help_text="e.g., 'Ch5/Ch6'", max_length=50, verbose_name='NL8-A Pair 3 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl8_a_pair_4',
            field=models.CharField(blank=True, help_text="e.g., 'Ch7/Ch8'", max_length=50, verbose_name='NL8-A Pair 4 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl8_b_pair_1',
            field=models.CharField(blank=True, help_text="e.g., 'Ch1/Ch2'", max_length=50, verbose_name='NL8-B Pair 1 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl8_b_pair_2',
            field=models.CharField(blank=True, help_text="e.g., 'Ch3/Ch4'", max_length=50, verbose_name='NL8-B Pair 2 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl8_b_pair_3',
            field=models.CharField(blank=True, help_text="e.g., 'Ch5/Ch6'", max_length=50, verbose_name='NL8-B Pair 3 +/-'),
        ),
        migrations.AddField(
            model_name='amp',
            name='nl8_b_pair_4',
            field=models.CharField(blank=True, help_text="e.g., 'Ch7/Ch8'", max_length=50, verbose_name='NL8-B Pair 4 +/-'),
        ),
        migrations.AddField(
            model_name='ampmodel',
            name='nl8_connector_count',
            field=models.IntegerField(choices=[(0, 'None'), (1, '1 NL8'), (2, '2 NL8')], default=0),
        ),
    ]
