# Generated by Django 5.2.4 on 2025-11-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0095_ampmodel_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amplifierprofile',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Amplifier Profile', 'verbose_name_plural': '    └─ Amplifier Profiles'},
        ),
        migrations.RemoveField(
            model_name='amp',
            name='cacom_1_assignment',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='cacom_2_assignment',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='cacom_3_assignment',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='cacom_4_assignment',
        ),
        migrations.RemoveField(
            model_name='ampmodel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_1_ch1',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 1 - Ch1'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_1_ch2',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 1 - Ch2'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_1_ch3',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 1 - Ch3'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_1_ch4',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 1 - Ch4'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_2_ch1',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 2 - Ch5'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_2_ch2',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 2 - Ch6'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_2_ch3',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 2 - Ch7'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_2_ch4',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 2 - Ch8'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_3_ch1',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 3 - Ch9'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_3_ch2',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 3 - Ch10'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_3_ch3',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 3 - Ch11'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_3_ch4',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 3 - Ch12'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_4_ch1',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 4 - Ch13'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_4_ch2',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 4 - Ch14'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_4_ch3',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 4 - Ch15'),
        ),
        migrations.AddField(
            model_name='amp',
            name='cacom_4_ch4',
            field=models.CharField(blank=True, max_length=100, verbose_name='CaCom 4 - Ch16'),
        ),
    ]
