# Generated by Django 5.2.4 on 2025-11-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0096_alter_amplifierprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampchannel',
            name='avb_stream',
            field=models.CharField(blank=True, help_text='AVB stream assignment', max_length=10, null=True, verbose_name='AVB Stream'),
        ),
    ]
