# Generated by Django 5.2.4 on 2025-11-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0097_alter_ampchannel_avb_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampchannel',
            name='avb_stream',
            field=models.CharField(blank=True, choices=[('', '---------'), ('AVB 1', 'AVB 1'), ('AVB 2', 'AVB 2'), ('AVB 3', 'AVB 3'), ('AVB 4', 'AVB 4'), ('AVB 5', 'AVB 5'), ('AVB 6', 'AVB 6'), ('AVB 7', 'AVB 7'), ('AVB 8', 'AVB 8'), ('AVB 9', 'AVB 9'), ('AVB 10', 'AVB 10'), ('AVB 11', 'AVB 11'), ('AVB 12', 'AVB 12'), ('AVB 13', 'AVB 13'), ('AVB 14', 'AVB 14'), ('AVB 15', 'AVB 15'), ('AVB 16', 'AVB 16')], help_text='AVB stream assignment', max_length=10, null=True, verbose_name='AVB Stream'),
        ),
    ]
