# Generated by Django 5.2.4 on 2025-11-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0098_alter_ampchannel_avb_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commposition',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='commposition',
            unique_together={('name', 'project')},
        ),
    ]
