# Generated by Django 5.2.4 on 2025-11-17 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0099_alter_commposition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commbeltpack',
            name='channel_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpack_channel_e', to='planner.commchannel', verbose_name='CH E'),
        ),
        migrations.AddField(
            model_name='commbeltpack',
            name='channel_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpack_channel_f', to='planner.commchannel', verbose_name='CH F'),
        ),
    ]
