# Generated by Django 5.2.4 on 2025-11-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0100_commbeltpack_channel_e_commbeltpack_channel_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='amp',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Background color for this amp in lists (hex code, e.g., #FF5733)', max_length=7, null=True),
        ),
    ]
