# Generated by Django 5.2.4 on 2025-11-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0101_amp_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampchannel',
            name='channel_name',
            field=models.CharField(blank=True, help_text="Signal type (e.g., 'PA', 'LF', 'HF', 'SUB')", max_length=100),
        ),
    ]
