# Generated by Django 5.2.4 on 2025-11-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0102_alter_ampchannel_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampchannel',
            name='channel_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='commbeltpack',
            name='headset',
            field=models.CharField(blank=True, choices=[('lw_single', 'LW Single'), ('hw_single', 'HW Single'), ('hw_double', 'HW Double'), ('personal', 'Personal')], max_length=20, verbose_name='Headset Type'),
        ),
    ]
