# Generated by Django 5.2.4 on 2025-11-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0103_alter_ampchannel_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commbeltpack',
            options={'ordering': ['system_type', 'manufacturer', 'bp_number'], 'verbose_name': 'Comm Belt Pack', 'verbose_name_plural': 'Comm Belt Packs'},
        ),
        migrations.AddField(
            model_name='commbeltpack',
            name='channel_g',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpack_channel_g', to='planner.commchannel', verbose_name='CH G'),
        ),
        migrations.AddField(
            model_name='commbeltpack',
            name='channel_h',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beltpack_channel_h', to='planner.commchannel', verbose_name='CH H'),
        ),
        migrations.AddField(
            model_name='commbeltpack',
            name='manufacturer',
            field=models.CharField(choices=[('clearcom_helixnet', 'Clear-Com HelixNet'), ('rts_partyline', 'RTS Partyline'), ('rts_odin', 'RTS ODIN Matrix'), ('riedel_performer', 'Riedel Performer'), ('clearcom_freespeak', 'Clear-Com FreeSpeak Edge/Icon'), ('riedel_bolero', 'Riedel Bolero'), ('rad_uv1g', 'Radio Active Designs RAD')], default='clearcom_helixnet', help_text='Belt pack system manufacturer', max_length=50, verbose_name='System/Manufacturer'),
        ),
    ]
