# Generated by Django 5.2.4 on 2025-11-22 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0104_alter_commbeltpack_options_commbeltpack_channel_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commbeltpack',
            name='channel_a',
        ),
        migrations.RemoveField(
            model_name='commbeltpack',
            name='channel_b',
        ),
        migrations.RemoveField(
            model_name='commbeltpack',
            name='channel_c',
        ),
        migrations.RemoveField(
            model_name='commbeltpack',
            name='channel_d',
        ),
        migrations.RemoveField(
            model_name='commbeltpack',
            name='channel_e',
        ),
        migrations.RemoveField(
            model_name='commbeltpack',
            name='channel_f',
        ),
        migrations.RemoveField(
            model_name='commbeltpack',
            name='channel_g',
        ),
        migrations.RemoveField(
            model_name='commbeltpack',
            name='channel_h',
        ),
        migrations.CreateModel(
            name='CommBeltPackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.PositiveIntegerField(help_text='Channel number (1, 2, 3, etc.)', verbose_name='Channel #')),
                ('beltpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='planner.commbeltpack')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.commchannel', verbose_name='Assignment')),
            ],
            options={
                'verbose_name': 'Belt Pack Channel',
                'verbose_name_plural': 'Belt Pack Channels',
                'ordering': ['channel_number'],
                'unique_together': {('beltpack', 'channel_number')},
            },
        ),
    ]
