# Generated by Django 5.2.4 on 2025-11-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0105_remove_commbeltpack_channel_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commcrewname',
            options={'ordering': ['name'], 'verbose_name': 'Comm Crew Name', 'verbose_name_plural': '    ├─ Comm Crew Names'},
        ),
        migrations.RemoveField(
            model_name='commchannel',
            name='input_designation',
        ),
        migrations.AlterField(
            model_name='commcrewname',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='commcrewname',
            unique_together={('name', 'project')},
        ),
    ]
