# Generated by Django 5.2.4 on 2025-11-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0106_alter_commcrewname_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pazone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.project'),
        ),
    ]
