# Generated by Django 5.2.4 on 2025-11-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0107_add_project_to_pazone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiochecklist',
            options={'ordering': ['name'], 'verbose_name': 'Audio Checklist', 'verbose_name_plural': 'Audio Checklists'},
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='label',
            field=models.ForeignKey(blank=True, help_text='Zone label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cables', to='planner.pazone', verbose_name='Label'),
        ),
        migrations.CreateModel(
            name='AudioChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('setup', 'Setup (One-Time)'), ('daily', 'Daily')], default='setup', max_length=10)),
                ('stage', models.CharField(blank=True, choices=[('', '-'), ('Pre-Production', 'Pre-Production'), ('Load-In', 'Load-In')], default='', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('day1_status', models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('complete', 'Complete'), ('na', 'N/A')], default='not-started', max_length=20)),
                ('day2_status', models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('complete', 'Complete'), ('na', 'N/A')], default='not-started', max_length=20)),
                ('day3_status', models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('complete', 'Complete'), ('na', 'N/A')], default='not-started', max_length=20)),
                ('day4_status', models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('complete', 'Complete'), ('na', 'N/A')], default='not-started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.audiochecklist')),
            ],
            options={
                'verbose_name': 'Audio Checklist Task',
                'verbose_name_plural': 'Audio Checklist Tasks',
                'ordering': ['checklist', 'task_type', 'sort_order'],
            },
        ),
    ]
