# Generated by Django 5.2.4 on 2025-12-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0108_alter_audiochecklist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='show_date',
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='Default Checklist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='name',
            field=models.CharField(default='Default Checklist', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='project',
            field=models.ForeignKey(default='Default Checklist', on_delete=django.db.models.deletion.CASCADE, related_name='audio_checklists', to='planner.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterUniqueTogether(
            name='audiochecklist',
            unique_together={('project', 'name')},
        ),
        migrations.AlterModelTable(
            name='audiochecklist',
            table=None,
        ),
    ]
