# Generated by Django 5.2.4 on 2025-12-03 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
            ('planner', '0108_alter_audiochecklist_options_and_more'),
        ]


    operations = [
        migrations.RemoveField(
            model_name='project',
            name='show_date',
        ),
        
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
       
      
    ]
