# Generated by Django 5.2.4 on 2025-12-03 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('planner', '0109_remove_project_show_date_audiochecklist_created_at_and_more'),
]

    operations = [
        
        migrations.AlterField(
            model_name='powerdistributionplan',
            name='show_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_plans', to='planner.showday'),
        ),
       
    ]
