# Generated by Django 5.2.4 on 2025-12-09 17:15
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0110_make_power_plan_show_day_optional"),
    ]
    
    # Migration operations skipped - already applied manually
    operations = []

