# Generated by Django 5.2.4 on 2025-12-09 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0110_make_power_plan_show_day_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audio_checklists', to='planner.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='showday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='audiochecklist',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='showday',
            unique_together={('project', 'date')},
        ),
        migrations.AlterModelTable(
            name='audiochecklist',
            table=None,
        ),
    ]
