# Generated by Django 5.2.4 on 2025-12-22 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0112_fix_showday_date_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audio_checklists', to='planner.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiochecklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commbeltpack',
            name='unit_location',
            field=models.ForeignKey(blank=True, help_text='Equipment location for this belt pack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_beltpacks', to='planner.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='showday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='audiochecklist',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='showday',
            unique_together={('project', 'date')},
        ),
        migrations.AlterModelTable(
            name='audiochecklist',
            table=None,
        ),
    ]
