# Generated by Django 5.2.4 on 2026-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0113_audiochecklist_created_at_audiochecklist_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ampchannel',
            options={'ordering': ['id'], 'verbose_name': 'Amp Channel', 'verbose_name_plural': 'Amp Channels'},
        ),
        migrations.AlterModelOptions(
            name='amplifierassignment',
            options={'ordering': ['id'], 'verbose_name': 'Amplifiers in Power Plan', 'verbose_name_plural': 'Amplifiers in Power Plan'},
        ),
        migrations.AlterModelOptions(
            name='amplifierprofile',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Amplifier Profile', 'verbose_name_plural': 'Amplifier Profiles'},
        ),
        migrations.AlterModelOptions(
            name='ampmodel',
            options={'ordering': ['id'], 'verbose_name': 'Amp Model Template', 'verbose_name_plural': 'Amp Model Templates'},
        ),
        migrations.AlterModelOptions(
            name='commchannel',
            options={'ordering': ['id'], 'verbose_name': 'Comm Channel', 'verbose_name_plural': 'Comm Channels'},
        ),
        migrations.AlterModelOptions(
            name='commcrewname',
            options={'ordering': ['name'], 'verbose_name': 'Comm Crew Name', 'verbose_name_plural': 'Comm Crew Names'},
        ),
        migrations.AlterModelOptions(
            name='commposition',
            options={'ordering': ['name'], 'verbose_name': 'Comm Position', 'verbose_name_plural': 'Comm Positions'},
        ),
        migrations.AlterModelOptions(
            name='micassignment',
            options={'ordering': ['rf_number'], 'verbose_name': 'Mic Assignment', 'verbose_name_plural': 'Mic Assignments'},
        ),
        migrations.AlterModelOptions(
            name='micsession',
            options={'ordering': ['day', 'order'], 'verbose_name': 'Mic Session', 'verbose_name_plural': 'Mic Sessions'},
        ),
        migrations.AlterModelOptions(
            name='micshowinfo',
            options={'verbose_name': 'Mic Show Information', 'verbose_name_plural': 'Mic Show Information'},
        ),
        migrations.AlterModelOptions(
            name='pafanout',
            options={'ordering': ['id'], 'verbose_name': 'PA Fan Out', 'verbose_name_plural': 'PA Fan Outs'},
        ),
        migrations.AlterModelOptions(
            name='presenter',
            options={'ordering': ['name'], 'verbose_name': 'Presenter', 'verbose_name_plural': 'Presenters'},
        ),
        migrations.AlterModelOptions(
            name='speakerarray',
            options={'ordering': ['prediction', 'array_base_name'], 'verbose_name': 'Speaker Array', 'verbose_name_plural': 'Speaker Arrays'},
        ),
        migrations.AlterModelOptions(
            name='speakercabinet',
            options={'ordering': ['id'], 'verbose_name': 'Speaker Cabinet', 'verbose_name_plural': 'Speaker Cabinets'},
        ),
        migrations.AddField(
            model_name='consoleinput',
            name='source_hardware',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Shure AD1', 'Shure AD1'), ('Shure AD2', 'Shure AD2'), ('Shure ADX1', 'Shure ADX1'), ('Shure ADX2', 'Shure ADX2'), ('Shure - Beta 87', 'Shure - Beta 87'), ('Sennheiser - MKH416', 'Sennheiser - MKH416'), ('Sennheiser - MD431', 'Sennheiser - MD431'), ('USB DI', 'USB DI'), ('AVIO', 'AVIO'), ('Arcadia Dante', 'Arcadia Dante'), ('RUIO-16', 'RUIO-16'), ('FOH', 'FOH'), ('RME', 'RME'), ('XLR', 'XLR'), ('Shure - B91', 'Shure - B91'), ('Shure - B52', 'Shure - B52'), ('Shure - B98', 'Shure - B98'), ('Shure - Beta 181', 'Shure - Beta 181'), ('Shure - SM58', 'Shure - SM58'), ('Shure - SM57', 'Shure - SM57'), ('Shure - KSM137', 'Shure - KSM137'), ('Shure - KSM141', 'Shure - KSM141'), ('Shure - KSM32', 'Shure - KSM32'), ('Shure - KSM27', 'Shure - KSM27'), ('Direct Box', 'Direct Box'), ('Sennheiser - e604', 'Sennheiser - e604'), ('Sennheiser - e901', 'Sennheiser - e901'), ('Sennheiser - e904', 'Sennheiser - e904'), ('Sennheiser - e906', 'Sennheiser - e906'), ('Sennheiser - e935s', 'Sennheiser - e935s'), ('Sennheiser - e945', 'Sennheiser - e945'), ('Sennheiser - MD421', 'Sennheiser - MD421')], max_length=50, null=True, verbose_name='Source Hardware'),
        ),
        migrations.AlterField(
            model_name='amplifierassignment',
            name='phase_assignment',
            field=models.CharField(choices=[('L1', 'Phase L1/A'), ('L2', 'Phase L2/B'), ('L3', 'Phase L3/C'), ('AUTO', 'Auto-Balance (distribute across phases)')], default='AUTO', max_length=10),
        ),
    ]
