# Generated by Django 5.2.4 on 2026-02-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0114_alter_ampchannel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoleinput',
            name='source_hardware',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Shure AD1', 'Shure AD1'), ('Shure AD2', 'Shure AD2'), ('Shure ADX1', 'Shure ADX1'), ('Shure ADX2', 'Shure ADX2'), ('Shure - Beta 87', 'Shure - Beta 87'), ('Senn - MKH416', 'Senn - MKH416'), ('Senn - MD431', 'Senn - MD431'), ('USB DI', 'USB DI'), ('AVIO', 'AVIO'), ('Arcadia Dante', 'Arcadia Dante'), ('RUIO-16', 'RUIO-16'), ('FOH', 'FOH'), ('RME', 'RME'), ('XLR', 'XLR'), ('Shure - B91', 'Shure - B91'), ('Shure - B52', 'Shure - B52'), ('Shure - B98', 'Shure - B98'), ('Shure - Beta 181', 'Shure - Beta 181'), ('Shure - SM58', 'Shure - SM58'), ('Shure - SM57', 'Shure - SM57'), ('Shure - KSM137', 'Shure - KSM137'), ('Shure - KSM141', 'Shure - KSM141'), ('Shure - KSM32', 'Shure - KSM32'), ('Shure - KSM27', 'Shure - KSM27'), ('Direct Box', 'Direct Box'), ('Senn - e604', 'Senn - e604'), ('Senn - e901', 'Senn - e901'), ('Senn - e904', 'Senn - e904'), ('Senn - e906', 'Senn - e906'), ('Senn - e935s', 'Senn - e935s'), ('Senn - e945', 'Senn - e945'), ('Senn - MD421', 'Senn - MD421')], max_length=50, null=True, verbose_name='Source Hardware'),
        ),
        migrations.AlterField(
            model_name='pazone',
            name='name',
            field=models.CharField(help_text='Short zone code (e.g., HL, HR, FF1)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='pazone',
            unique_together={('project', 'name')},
        ),
    ]
