# Generated by Django 5.2.4 on 2026-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0115_pazone_unique_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacableschedule',
            name='cable',
            field=models.CharField(choices=[('NL4_JUMPER', 'NL4 Jumper'), ('NL_4', 'NL 4'), ('CA-COM', 'CA-COM'), ('SC32', 'SC32'), ('NL_8', 'NL 8'), ('XLR', 'XLR'), ('XLR_FAN', 'XLR Fan'), ('AES_XLR', 'AES/EBU XLR'), ('L21-30', 'L21-30 Power'), ('EDISON_20_AMP', 'Edison 20amp')], default='100_NL4', max_length=20, verbose_name='Cable'),
        ),
    ]
