# Generated by Django 5.2.4 on 2026-02-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0116_add_sc32_cable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampmodel',
            name='sc32_connector_count',
            field=models.IntegerField(choices=[(0, 'None'), (1, '1 SC32')], default=0),
        ),
    ]
