# Generated by Django 5.2.4 on 2026-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0117_ampmodel_sc32_connector_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='amp',
            name='sc32_ch1',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch1'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch10',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch10'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch11',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch11'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch12',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch12'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch13',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch13'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch14',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch14'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch15',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch15'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch16',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch16'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch2',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch2'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch3',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch3'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch4',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch4'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch5',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch5'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch6',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch6'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch7',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch7'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch8',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch8'),
        ),
        migrations.AddField(
            model_name='amp',
            name='sc32_ch9',
            field=models.CharField(blank=True, max_length=100, verbose_name='SC32 - Ch9'),
        ),
    ]
