# Generated by Django 5.2.4 on 2026-02-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0118_amp_sc32_ch1_amp_sc32_ch10_amp_sc32_ch11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampchannel',
            name='channel_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
