# Generated by Django 5.2.4 on 2026-02-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0119_alter_ampchannel_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pazone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pazone',
            name='location',
        ),
    ]
