# Generated by Django 5.2.4 on 2026-02-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0120_remove_pazone_description_remove_pazone_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacableschedule',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Row background color (hex code)', max_length=7, null=True),
        ),
    ]
