# Generated by Django 5.2.4 on 2026-02-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0121_pacableschedule_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pafanout',
            name='extension_cable',
            field=models.CharField(blank=True, choices=[('', 'None'), ('NL4', 'NL4'), ('NL8', 'NL8')], default='', max_length=10, verbose_name='Extension Cable'),
        ),
        migrations.AddField(
            model_name='pafanout',
            name='extension_length',
            field=models.IntegerField(choices=[(0, 'None'), (6, "6'"), (25, "25'"), (50, "50'"), (100, "100'"), (150, "150'")], default=0, verbose_name='Extension Length'),
        ),
    ]
