# Generated by Django 5.2.4 on 2026-02-21 18:26 (manually edited)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0122_pafanout_extension_cable_pafanout_extension_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='micassignment',
            name='output_level',
            field=models.CharField(blank=True, choices=[('', '---'), ('LOW', 'Low (1–2 mW)'), ('MEDIUM', 'Medium (10 mW)'), ('HIGH', 'High (20–50 mW)')], help_text='Transmitter RF output level', max_length=10),
        ),
        migrations.AddField(
            model_name='micassignment',
            name='photo',
            field=models.ImageField(blank=True, help_text='Presenter headshot for A2 view', null=True, upload_to='presenter_photos/'),
        ),
        migrations.AddField(
            model_name='micassignment',
            name='placement',
            field=models.CharField(blank=True, choices=[('', '---'), ('LEFT_EAR', 'Left Ear'), ('RIGHT_EAR', 'Right Ear'), ('TIE', 'Tie'), ('LAV_MAGNET', 'Lav Magnet'), ('COLLAR', 'Collar'), ('HAIR_MOUNT', 'Hair Mount'), ('CHEEK', 'Cheek Mount'), ('FOREHEAD', 'Forehead'), ('CHEST_POCKET', 'Chest Pocket'), ('BELT_CLIP', 'Belt Clip')], help_text='Mic placement on primary presenter', max_length=20),
        ),
        migrations.AddField(
            model_name='micassignment',
            name='sensitivity',
            field=models.CharField(blank=True, choices=[('', '---'), ('-20', '-20 dB'), ('-18', '-18 dB'), ('-15', '-15 dB'), ('-12', '-12 dB'), ('-10', '-10 dB'), ('-9', '-9 dB'), ('-6', '-6 dB'), ('-3', '-3 dB'), ('0', '0 dB'), ('+3', '+3 dB'), ('+6', '+6 dB'), ('+9', '+9 dB'), ('+12', '+12 dB'), ('+15', '+15 dB'), ('+18', '+18 dB'), ('+20', '+20 dB')], help_text='Transmitter input sensitivity', max_length=10),
        ),
        migrations.CreateModel(
            name='SharedPresenterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(blank=True, choices=[('', '---'), ('LEFT_EAR', 'Left Ear'), ('RIGHT_EAR', 'Right Ear'), ('TIE', 'Tie'), ('LAV_MAGNET', 'Lav Magnet'), ('COLLAR', 'Collar'), ('HAIR_MOUNT', 'Hair Mount'), ('CHEEK', 'Cheek Mount'), ('FOREHEAD', 'Forehead'), ('CHEST_POCKET', 'Chest Pocket'), ('BELT_CLIP', 'Belt Clip')], max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('mic_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_presenter_assignments', to='planner.micassignment')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_assignments', to='planner.presenter')),
            ],
            options={
                'verbose_name': 'Shared Presenter Assignment',
                'verbose_name_plural': 'Shared Presenter Assignments',
                'ordering': ['order', 'id'],
            },
        ),
        # NOTE: AlterField for shared_presenters deliberately removed.
        # The through= relationship is already declared in the model.
        # Django will reconcile the M2M state via the CreateModel above.
    ]
