# Generated by Django 5.2.4 on 2026-02-22 15:39
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('planner', '0123_mic_tracker_a2_fields'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='showday',
            options={'ordering': ['date'], 'verbose_name': 'Day', 'verbose_name_plural': 'Mic Tracker'},
        ),
        migrations.AlterField(
            model_name='micassignment',
            name='output_level',
            field=models.CharField(blank=True, choices=[('', '---'), ('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High'), ('0DBU', '0 dBu'), ('6DBU', '+6 dBu'), ('12DBU', '+12 dBu'), ('18DBU', '+18 dBu'), ('0DBV', '0 dBV'), ('6DBV', '+6 dBV'), ('12DBV', '+12 dBV')], help_text='Transmitter RF output level', max_length=10),
        ),
    ]