# Generated by Django 5.2.4 on 2026-02-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0124_alter_showday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micassignment',
            name='mic_type',
            field=models.CharField(blank=True, choices=[('', '---'), ('HH', 'Handheld'), ('LAV', 'Lav'), ('HEADSET', 'Headset'), ('PODIUM', 'Podium'), ('BOOM', 'Boom'), ('INSTRUMENT', 'Instrument')], max_length=20),
        ),
        
        migrations.CreateModel(
            name='MicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('amber', 'Amber'), ('red', 'Red'), ('purple', 'Purple'), ('teal', 'Teal')], default='blue', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mic_groups', to='planner.micsession')),
            ],
        ),
        migrations.AddField(
            model_name='micassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='planner.micgroup'),
        ),
    ]
