# Generated by Django 5.2.4 on 2026-02-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0125_alter_micassignment_mic_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micassignment',
            name='shared_presenters',
            field=models.ManyToManyField(blank=True, help_text='Additional presenters sharing this mic', related_name='shared_mic_assignments', through='planner.SharedPresenterAssignment', to='planner.presenter'),
        ),
    ]
