# Generated by Django 5.2.4 on 2026-02-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0126_alter_micassignment_shared_presenters'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='photo',
            field=models.ImageField(blank=True, help_text='Presenter headshot', null=True, upload_to='presenter_photos/'),
        ),
    ]
