# Generated by Django 5.2.4 on 2026-02-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0127_presenter_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenterSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('mic_type', models.CharField(blank=True, choices=[('', '---'), ('HH', 'Handheld'), ('LAV', 'Lav'), ('HEADSET', 'Headset'), ('PODIUM', 'Podium'), ('BOOM', 'Boom'), ('INSTRUMENT', 'Instrument')], max_length=20)),
                ('placement', models.CharField(blank=True, choices=[('', '---'), ('LEFT_EAR', 'Left Ear'), ('RIGHT_EAR', 'Right Ear'), ('TIE', 'Tie'), ('LAV_MAGNET', 'Lav Magnet'), ('COLLAR', 'Collar'), ('HAIR_MOUNT', 'Hair Mount'), ('CHEEK', 'Cheek Mount'), ('FOREHEAD', 'Forehead'), ('CHEST_POCKET', 'Chest Pocket'), ('BELT_CLIP', 'Belt Clip')], max_length=20)),
                ('sensitivity', models.CharField(blank=True, choices=[('', '---'), ('-20', '-20 dB'), ('-18', '-18 dB'), ('-15', '-15 dB'), ('-12', '-12 dB'), ('-10', '-10 dB'), ('-9', '-9 dB'), ('-6', '-6 dB'), ('-3', '-3 dB'), ('0', '0 dB'), ('+3', '+3 dB'), ('+6', '+6 dB'), ('+9', '+9 dB'), ('+12', '+12 dB'), ('+15', '+15 dB'), ('+18', '+18 dB'), ('+20', '+20 dB')], max_length=10)),
                ('output_level', models.CharField(blank=True, choices=[('', '---'), ('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High'), ('0DBU', '0 dBu'), ('6DBU', '+6 dBu'), ('12DBU', '+12 dBu'), ('18DBU', '+18 dBu'), ('0DBV', '0 dBV'), ('6DBV', '+6 dBV'), ('12DBV', '+12 dBV')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenter_slots', to='planner.micassignment')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='planner.presenter')),
            ],
            options={
                'verbose_name': 'Presenter Slot',
                'ordering': ['order'],
            },
        ),
    ]
