# Generated by Django 5.2.4 on 2026-02-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0128_presenterslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micassignment',
            name='presenter',
        ),
        migrations.AddField(
            model_name='presenterslot',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo for this presenter slot', null=True, upload_to='slot_photos/'),
        ),
    ]
