# Generated by Django 5.2.4 on 2026-02-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0129_remove_micassignment_presenter_presenterslot_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenterslot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_assignments', to='planner.micgroup'),
        ),
        migrations.AddField(
            model_name='presenterslot',
            name='is_micd',
            field=models.BooleanField(default=False),
        ),
    ]
