# Generated by Django 5.2.4 on 2026-03-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0130_presenterslot_group_presenterslot_is_micd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Equip Location', 'verbose_name_plural': 'Equip Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
