# Generated by Django 5.2.4 on 2026-03-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0131_alter_location_options_location_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenterslot',
            name='photo_data',
            field=models.TextField(blank=True, help_text='Base64 encoded photo data', null=True),
        ),
    ]
