# Generated by Django 5.2.4 on 2026-03-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0132_presenterslot_photo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenterslot',
            name='a2_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_a2_assignments', to='planner.micgroup'),
        ),
    ]
