# Generated by Django 5.2.4 on 2026-03-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0133_add_presenterslot_a2_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='amp',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Order within location group'),
        ),
    ]
