# Generated by Django 5.2.4 on 2026-03-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0134_add_amp_sort_order_and_divider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpDivider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amp_dividers', to='planner.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.project')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
