# Generated by Django 5.2.4 on 2026-03-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0135_add_amp_divider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'GJS Corporate Template')", max_length=100)),
                ('device_type', models.CharField(choices=[('arcadia', 'Clear-Com Arcadia'), ('freespeak', 'Clear-Com FreeSpeak II'), ('helixnet', 'Clear-Com HelixNet')], default='arcadia', max_length=20)),
                ('system_id', models.CharField(blank=True, help_text='8-char system ID (auto-generated or from imported .cca)', max_length=8)),
                ('hardware_id', models.CharField(blank=True, help_text='Hardware MAC ID from unit (e.g., ff080f1f)', max_length=8)),
                ('wireless_region', models.IntegerField(choices=[(0, 'US/Canada'), (1, 'Europe'), (2, 'Japan'), (3, 'Australia'), (4, 'Brazil'), (5, 'China')], default=0)),
                ('wireless_id', models.CharField(blank=True, max_length=3)),
                ('admin_pin', models.CharField(default='1111', max_length=4)),
                ('ota_pin', models.CharField(default='0000', max_length=4)),
                ('display_brightness', models.IntegerField(default=170)),
                ('touch_sensitivity', models.IntegerField(default=1)),
                ('battery_type', models.CharField(choices=[('Alkaline', 'Alkaline'), ('NiMH', 'NiMH'), ('Lithium', 'Lithium')], default='Alkaline', max_length=10)),
                ('dsp_plc_state', models.BooleanField(default=False, verbose_name='DSP PLC')),
                ('disable_http', models.BooleanField(default=False)),
                ('role_sorting', models.CharField(choices=[('RoleNumber', 'By Role Number'), ('RoleName', 'By Role Name')], default='RoleNumber', max_length=20)),
                ('antenna_0_connector', models.CharField(choices=[('rj45', 'RJ45'), ('fiber', 'Fiber')], default='rj45', max_length=10, verbose_name='Antenna Port 0')),
                ('antenna_1_connector', models.CharField(choices=[('rj45', 'RJ45'), ('fiber', 'Fiber')], default='rj45', max_length=10, verbose_name='Antenna Port 1')),
                ('factory_base_json', models.JSONField(blank=True, default=dict)),
                ('admin_username', models.CharField(default='admin', max_length=50)),
                ('admin_password_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.project')),
            ],
            options={
                'verbose_name': 'COMM Configuration',
                'verbose_name_plural': 'COMM Configurations',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='CommConfigPartyline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.IntegerField()),
                ('label', models.CharField(max_length=20)),
                ('helixnet_enabled', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partylines', to='planner.commconfig')),
            ],
            options={
                'verbose_name': 'Config Partyline',
                'verbose_name_plural': 'Config Partylines',
                'ordering': ['channel_number'],
                'unique_together': {('config', 'channel_number')},
            },
        ),
        migrations.CreateModel(
            name='CommConfigPortAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_type', models.CharField(choices=[('2W', '2-Wire'), ('4W', '4-Wire'), ('Dante', 'Dante'), ('HelixNet', 'HelixNet'), ('SA', 'Stage Announce'), ('PGM', 'Program')], max_length=10)),
                ('port_label', models.CharField(max_length=30)),
                ('port_gid', models.CharField(max_length=60)),
                ('join_mode', models.CharField(choices=[('Talk-Listen', 'Talk + Listen'), ('Talk', 'Talk Only'), ('Listen', 'Listen Only')], default='Talk-Listen', max_length=15)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_assignments', to='planner.commconfig')),
                ('partyline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_assignments', to='planner.commconfigpartyline')),
            ],
            options={
                'verbose_name': 'Config Port Assignment',
                'verbose_name_plural': 'Config Port Assignments',
                'ordering': ['port_type', 'port_label'],
            },
        ),
        migrations.CreateModel(
            name='CommConfigRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_number', models.IntegerField()),
                ('device_type', models.CharField(choices=[('FSII-BP', 'FreeSpeak II Beltpack'), ('E-BP', 'FreeSpeak Edge Beltpack'), ('HBP-2X', 'HelixNet Beltpack (2-key)'), ('HKB-2X', 'HelixNet Keypanel (2-key)'), ('HMS-4X', 'HMS Station (4-key)'), ('HRM-4X', 'HRM Remote (4-key)'), ('NEP', 'Arcadia Station / Panel'), ('V12', 'V-Panel 12 Key'), ('V24', 'V-Panel 24 Key'), ('V32', 'V-Panel 32 Key'), ('V12D', 'V-Panel 12 Key Desktop'), ('LQ-AIC', 'Agent-IC')], max_length=10)),
                ('label', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('sidetone_gain', models.FloatField(default=-9.6)),
                ('sidetone_control', models.CharField(choices=[('tracking', 'Tracking'), ('fixed', 'Fixed')], default='tracking', max_length=10)),
                ('headphone_limit', models.IntegerField(default=0)),
                ('headphone_gain', models.IntegerField(default=0)),
                ('mic_type', models.CharField(choices=[('automatic', 'Automatic'), ('dynamic', 'Dynamic'), ('dynamic_0', 'Dynamic (0dB)'), ('electret', 'Electret')], default='automatic', max_length=20)),
                ('master_volume', models.FloatField(default=-9.6)),
                ('display_brightness', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10)),
                ('extended_settings', models.JSONField(blank=True, default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='planner.commconfig')),
            ],
            options={
                'verbose_name': 'Config Role',
                'verbose_name_plural': 'Config Roles',
                'ordering': ['is_default', 'role_number'],
                'unique_together': {('config', 'role_number')},
            },
        ),
        migrations.CreateModel(
            name='CommConfigRoleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleset_number', models.IntegerField()),
                ('label', models.CharField(max_length=20)),
                ('addressable', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolesets', to='planner.commconfig')),
            ],
            options={
                'verbose_name': 'Config Roleset',
                'verbose_name_plural': 'Config Rolesets',
                'ordering': ['roleset_number'],
                'unique_together': {('config', 'roleset_number')},
            },
        ),
        migrations.CreateModel(
            name='CommConfigSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('B.FSII', 'FreeSpeak II Beltpack'), ('B.HBP', 'HelixNet Beltpack'), ('B.HKB', 'HelixNet Keypanel'), ('S.NEP', 'Station / Arcadia Panel'), ('A.CCM', 'Admin (CCM)')], max_length=10)),
                ('label', models.CharField(max_length=20)),
                ('addressable', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planner.commconfig')),
                ('default_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sessions', to='planner.commconfigrole')),
                ('roleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='planner.commconfigroleset')),
            ],
            options={
                'verbose_name': 'Config Session',
                'verbose_name_plural': 'Config Sessions',
                'ordering': ['session_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CommConfigKeyset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_index', models.IntegerField()),
                ('entity_type', models.IntegerField(blank=True, choices=[(0, 'Partyline / Channel'), (1, 'Port / Direct')], null=True)),
                ('port_reference', models.CharField(blank=True, max_length=100)),
                ('activation_state', models.CharField(choices=[('talkforcelisten', 'Talk + Force Listen'), ('talklisten', 'Talk + Listen'), ('talk', 'Talk Only'), ('listen', 'Listen Only')], default='talkforcelisten', max_length=20)),
                ('talk_mode', models.CharField(choices=[('latching', 'Latching'), ('non-latching', 'Non-Latching (Momentary)'), ('disabled', 'Disabled')], default='latching', max_length=15)),
                ('is_call_key', models.BooleanField(default=False)),
                ('is_reply_key', models.BooleanField(default=False)),
                ('in_use_tally', models.BooleanField(default=True)),
                ('minimum_volume', models.IntegerField(default=0)),
                ('maximum_volume', models.IntegerField(default=29)),
                ('interlock_group', models.BooleanField(default=False)),
                ('partyline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyset_assignments', to='planner.commconfigpartyline')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keysets', to='planner.commconfigrole')),
            ],
            options={
                'verbose_name': 'Config Keyset',
                'verbose_name_plural': 'Config Keysets',
                'ordering': ['key_index'],
                'unique_together': {('role', 'key_index')},
            },
        ),
    ]
