# Generated by Django 5.2.4 on 2026-03-15 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0136_commconfig_commconfigpartyline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commconfigportassignment',
            name='partyline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_assignments', to='planner.commconfigpartyline'),
        ),
        migrations.CreateModel(
            name='CommConfigDanteChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.IntegerField()),
                ('label', models.CharField(max_length=40)),
                ('direction', models.CharField(choices=[('send', 'Send (Output)'), ('receive', 'Receive (Input)')], default='receive', max_length=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dante_channels', to='planner.commconfig')),
                ('partyline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dante_channels', to='planner.commconfigpartyline')),
            ],
            options={
                'verbose_name': 'Dante Channel',
                'verbose_name_plural': 'Dante Channels',
                'ordering': ['direction', 'channel_number'],
                'unique_together': {('config', 'direction', 'channel_number')},
            },
        ),
    ]
