# Generated by Django 5.2.4 on 2026-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0137_comm_config_nullable_port_dante_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commconfigportassignment',
            name='mode_2w',
            field=models.CharField(blank=True, choices=[('clearcom', 'Clear-Com'), ('rts', 'RTS')], default='clearcom', max_length=10),
        ),
        migrations.AddField(
            model_name='commconfigportassignment',
            name='output_level',
            field=models.CharField(blank=True, choices=[('line', 'Line Level (0dB)'), ('mic', 'Mic Level (-55dB)')], default='line', max_length=10),
        ),
        migrations.AddField(
            model_name='commconfigportassignment',
            name='port_function',
            field=models.CharField(blank=True, choices=[('4wire-x', '4-Wire-X (To Matrix)'), ('4wire', '4-Wire (To Panel)')], default='4wire-x', max_length=10),
        ),
        migrations.AddField(
            model_name='commconfigportassignment',
            name='power_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commconfigportassignment',
            name='receive_call_signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commconfigportassignment',
            name='termination_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
