# Generated by Django 5.2.4 on 2026-03-20 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0138_comm_config_port_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='planner.project')),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AudioChecklistTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('section', models.CharField(choices=[('FOH', 'FOH'), ('A2', 'A2'), ('Prep', 'Prep')], default='FOH', max_length=10)),
                ('task_type', models.CharField(choices=[('setup', 'Setup (One-Time)'), ('daily', 'Daily')], default='setup', max_length=10)),
                ('stage', models.CharField(blank=True, choices=[('', '-'), ('Pre-Production', 'Pre-Production'), ('Load-In', 'Load-In')], default='', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.audiochecklisttemplate')),
            ],
            options={
                'verbose_name': 'Template Task',
                'verbose_name_plural': 'Template Tasks',
                'ordering': ['template', 'section', 'task_type', 'sort_order'],
            },
        ),
    ]
