# Generated by Django 5.2.4 on 2026-03-28 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0139_audio_checklist_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invite_token',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.RunPython(
            lambda apps, se: [
                setattr(p, 'invite_token', uuid.uuid4()) or p.save(update_fields=['invite_token'])
                for p in apps.get_model('planner', 'Project').objects.all()
            ],
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='project',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commconfigrole',
            name='device_type',
            field=models.CharField(choices=[('FSII-BP', 'FreeSpeak II Beltpack'), ('E-BP', 'FreeSpeak Edge Beltpack'), ('HBP-2X', 'HelixNet Beltpack (2-key)'), ('HMS-4X', 'HMS Station (4-key)'), ('HRM-4X', 'HRM Remote (4-key)'), ('V12', 'V-Panel 12 Key'), ('V24', 'V-Panel 24 Key'), ('V32', 'V-Panel 32 Key')], max_length=10),
        ),
        migrations.CreateModel(
            name='ProjectAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_role', models.CharField(blank=True, choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=20, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from requester')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='planner.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('project', 'requester')},
            },
        ),
    ]
