# Generated by Django 5.2.4 on 2026-04-01 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0140_project_invite_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommConfigLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(choices=[('admin', 'LAN 1 — Management'), ('aes67', 'LAN 2 — AES67'), ('aes67Secondary', 'LAN 3 — AES67 Secondary'), ('danteprim', 'LAN 4 — Dante Primary')], max_length=20)),
                ('mode', models.CharField(choices=[('dhcp', 'DHCP (Dynamic)'), ('static', 'Static')], default='dhcp', max_length=10)),
                ('static_ip', models.CharField(blank=True, default='', max_length=15)),
                ('netmask', models.CharField(blank=True, default='', max_length=15)),
                ('gateway', models.CharField(blank=True, default='', max_length=15)),
                ('dns1', models.CharField(blank=True, default='', max_length=15)),
                ('dns2', models.CharField(blank=True, default='', max_length=15)),
                ('rear_connector', models.IntegerField(choices=[(1, 'Connector 1'), (2, 'Connector 2'), (255, 'None')], default=1)),
                ('ptp_follower_mode', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lans', to='planner.commconfig')),
            ],
            options={
                'verbose_name': 'Config LAN',
                'verbose_name_plural': 'Config LANs',
                'ordering': ['interface'],
                'unique_together': {('config', 'interface')},
            },
        ),
    ]
