# Generated by Django 5.2.4 on 2026-04-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0141_comm_config_lan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommConfigNetworkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('traffic_type', models.CharField(choices=[('disabled', 'Disabled'), ('admin', 'Management'), ('aes67', 'AES67'), ('aes67Secondary', 'AES67 Secondary'), ('danteprim', 'Dante Primary')], default='disabled', max_length=20)),
                ('mode', models.CharField(choices=[('dhcp', 'DHCP (Dynamic)'), ('static', 'Static')], default='dhcp', max_length=10)),
                ('static_ip', models.CharField(blank=True, default='', max_length=15)),
                ('netmask', models.CharField(blank=True, default='', max_length=15)),
                ('gateway', models.CharField(blank=True, default='', max_length=15)),
                ('dns1', models.CharField(blank=True, default='', max_length=15)),
                ('dns2', models.CharField(blank=True, default='', max_length=15)),
                ('ptp_follower_mode', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_ports', to='planner.commconfig')),
            ],
            options={
                'verbose_name': 'Network Port',
                'verbose_name_plural': 'Network Ports',
                'ordering': ['port_number'],
                'unique_together': {('config', 'port_number')},
            },
        ),
        migrations.DeleteModel(
            name='CommConfigLAN',
        ),
    ]
