# Generated by Django 5.2.4 on 2026-04-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0142_replace_commconfiglan_with_networkport'),
    ]

    operations = [
        migrations.AddField(
            model_name='commconfignetworkport',
            name='dante_redundancy',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10),
        ),
        migrations.AlterField(
            model_name='commconfignetworkport',
            name='traffic_type',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('admin', 'Management'), ('aes67', 'AES67'), ('dante', 'Dante')], default='disabled', max_length=20),
        ),
    ]
