# Generated by Django 5.2.4 on 2026-04-02 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0143_add_dante_redundancy_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='commconfig',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commconfig',
            name='template_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='console',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.project'),
        ),
    ]
