# Generated by Django 5.2.4 on 2026-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0144_comm_config_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='commconfigrole',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
