# Generated by Django 5.2.4 on 2026-04-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0145_commconfigrole_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanteConsoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dante_name', models.CharField(help_text='Dante network device name — must match exactly (case-sensitive).', max_length=100)),
                ('sample_rate', models.IntegerField(choices=[(44100, '44.1 kHz'), (48000, '48 kHz'), (88200, '88.2 kHz'), (96000, '96 kHz')], default=48000, verbose_name='Sample Rate')),
                ('encoding', models.IntegerField(choices=[(16, '16-bit'), (24, '24-bit'), (32, '32-bit')], default=24, verbose_name='Bit Depth')),
                ('tx_channel_count', models.PositiveIntegerField(default=0, help_text='Number of Dante send (TX) channels this device advertises.', verbose_name='TX Channel Count')),
                ('rx_channel_count', models.PositiveIntegerField(default=0, help_text='Number of Dante receive (RX) channels this device has.', verbose_name='RX Channel Count')),
                ('tx_channel_labels', models.JSONField(blank=True, default=list, help_text='JSON list of TX channel names. e.g. ["Main L", "Main R", ""]', verbose_name='TX Channel Labels')),
                ('rx_channel_labels', models.JSONField(blank=True, default=list, help_text='JSON list of RX channel names.', verbose_name='RX Channel Labels')),
                ('is_clock_master', models.BooleanField(default=False, help_text='Designate this device as the Dante clock master.', verbose_name='Clock Master')),
                ('clock_subdomain', models.CharField(blank=True, default='', help_text='Dante clock subdomain (leave blank for default subdomain).', max_length=50, verbose_name='Clock Subdomain')),
                ('console', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dante_config', to='planner.console')),
            ],
            options={
                'verbose_name': 'Dante Console Config',
                'verbose_name_plural': 'Dante Console Configs',
            },
        ),
        migrations.CreateModel(
            name='DanteDeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dante_name', models.CharField(help_text='Dante network device name — must match exactly (case-sensitive).', max_length=100)),
                ('sample_rate', models.IntegerField(choices=[(44100, '44.1 kHz'), (48000, '48 kHz'), (88200, '88.2 kHz'), (96000, '96 kHz')], default=48000, verbose_name='Sample Rate')),
                ('encoding', models.IntegerField(choices=[(16, '16-bit'), (24, '24-bit'), (32, '32-bit')], default=24, verbose_name='Bit Depth')),
                ('tx_channel_count', models.PositiveIntegerField(default=0, verbose_name='TX Channel Count')),
                ('rx_channel_count', models.PositiveIntegerField(default=0, verbose_name='RX Channel Count')),
                ('tx_channel_labels', models.JSONField(blank=True, default=list, verbose_name='TX Channel Labels')),
                ('rx_channel_labels', models.JSONField(blank=True, default=list, verbose_name='RX Channel Labels')),
                ('is_clock_master', models.BooleanField(default=False, verbose_name='Clock Master')),
                ('clock_subdomain', models.CharField(blank=True, default='', max_length=50, verbose_name='Clock Subdomain')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dante_config', to='planner.device')),
            ],
            options={
                'verbose_name': 'Dante Device Config',
                'verbose_name_plural': 'Dante Device Configs',
            },
        ),
        migrations.CreateModel(
            name='DanteSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_channel', models.PositiveIntegerField(verbose_name='RX Channel #')),
                ('rx_channel_name', models.CharField(help_text="Name as it appears on the RX device's Dante channel.", max_length=100, verbose_name='RX Channel Name')),
                ('tx_channel', models.PositiveIntegerField(verbose_name='TX Channel #')),
                ('tx_channel_name', models.CharField(help_text='TX channel name that will appear in subscribed_channel tag.', max_length=100, verbose_name='TX Channel Name')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dante_subscriptions', to='planner.project')),
                ('rx_console', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dante_rx_subscriptions', to='planner.console', verbose_name='RX Console')),
                ('rx_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dante_rx_subscriptions', to='planner.device', verbose_name='RX Device')),
                ('tx_console', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dante_tx_subscriptions', to='planner.console', verbose_name='TX Console')),
                ('tx_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dante_tx_subscriptions', to='planner.device', verbose_name='TX Device')),
            ],
            options={
                'verbose_name': 'Dante Subscription',
                'verbose_name_plural': 'Dante Subscriptions',
                'ordering': ['rx_console', 'rx_device', 'rx_channel'],
            },
        ),
    ]
