# Generated by Django 5.2.4 on 2026-04-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0146_danteconsoleconfig_dantedeviceconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='parent_console',
            field=models.ForeignKey(blank=True, help_text='For slot cards (e.g. Rivage Dante cards) — the console this card belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_devices', to='planner.console', verbose_name='Parent Console'),
        ),
    ]
