# Generated by Django 5.2.4 on 2026-04-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0147_device_parent_console'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('domain', models.CharField(choices=[('la_network', 'LA Network'), ('dante', 'Dante'), ('switch', 'Switch'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_known_state', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_devices', to='planner.project')),
            ],
            options={
                'ordering': ['domain', 'label', 'ip_address'],
                'unique_together': {('project', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='MonitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_sessions', to='planner.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('ONLINE', 'Came online'), ('OFFLINE', 'Went offline'), ('SCAN_STARTED', 'Network scan started'), ('MONITOR_STARTED', 'Monitor started')], max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.discovereddevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.monitorsession')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['session', 'occurred_at'], name='planner_dev_session_d5a1ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polled_at', models.DateTimeField(auto_now_add=True)),
                ('is_reachable', models.BooleanField()),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_results', to='planner.discovereddevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_results', to='planner.monitorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'polled_at'], name='planner_pol_device__b30f28_idx'), models.Index(fields=['session', 'polled_at'], name='planner_pol_session_fbd5c5_idx')],
            },
        ),
    ]
