# Generated by Django 5.2.4 on 2026-04-22 22:08
# Modified: 3-step migration to add unique UUIDs to existing rows

import uuid
from django.db import migrations, models


def generate_unique_api_keys(apps, schema_editor):
    """Assign a unique UUID to each existing project."""
    Project = apps.get_model('planner', 'Project')
    for project in Project.objects.all():
        project.agent_api_key = uuid.uuid4()
        project.save(update_fields=['agent_api_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0148_discovereddevice_monitorsession_deviceevent_and_more'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='project',
            name='agent_api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='API key for the local network monitor agent',
                                   null=True),
        ),
        # Step 2: Populate unique values for existing rows
        migrations.RunPython(generate_unique_api_keys, migrations.RunPython.noop),
        # Step 3: Add unique constraint and remove null
        migrations.AlterField(
            model_name='project',
            name='agent_api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='API key for the local network monitor agent',
                                   unique=True),
        ),
    ]
