# Generated by Django 5.2.4 on 2026-04-25 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0149_project_agent_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsession',
            name='show_mode',
            field=models.CharField(choices=[('setup', 'Setup'), ('show', 'Show'), ('wrap', 'Wrap')], default='show', max_length=10),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='event_type',
            field=models.CharField(choices=[('ONLINE', 'Came online'), ('OFFLINE', 'Went offline'), ('SCAN_STARTED', 'Network scan started'), ('MONITOR_STARTED', 'Monitor started'), ('PORT_DOWN', 'Switch port went down'), ('PORT_UP', 'Switch port came up'), ('BW_WARNING', 'Bandwidth threshold exceeded'), ('BW_CRITICAL', 'Bandwidth critical threshold exceeded')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectSNMPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_string', models.CharField(default='public', help_text='SNMP v2c community string for all switches in this project.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_config', to='planner.project')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchPortSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_index', models.PositiveIntegerField()),
                ('port_description', models.CharField(blank=True, max_length=100)),
                ('oper_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('speed_mbps', models.PositiveIntegerField(blank=True, null=True)),
                ('bandwidth_pct', models.FloatField(blank=True, null=True)),
                ('error_count', models.PositiveBigIntegerField(default=0)),
                ('polled_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_snapshots', to='planner.discovereddevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_snapshots', to='planner.monitorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'session'], name='planner_swi_device__16244b_idx')],
                'unique_together': {('device', 'session', 'port_index')},
            },
        ),
    ]
