# Generated by Django 5.2.4 on 2026-04-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0150_monitorsession_show_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovereddevice',
            name='clock_role',
            field=models.CharField(choices=[('master', 'Master'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('unknown', 'Unknown')], default='unknown', help_text='PTP clock role: master, locked, unlocked, or unknown (advisory)', max_length=20),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='dante_device_name',
            field=models.CharField(blank=True, help_text='Device name from Dante mDNS discovery (may differ from label)', max_length=200),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='dante_mac_address',
            field=models.CharField(blank=True, help_text='Dante interface MAC address from mDNS', max_length=20),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='dante_model_id',
            field=models.CharField(blank=True, help_text='Dante hardware model identifier from mDNS', max_length=50),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='rx_channel_count',
            field=models.PositiveIntegerField(blank=True, help_text='Dante receive channel count from protocol query', null=True),
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='tx_channel_count',
            field=models.PositiveIntegerField(blank=True, help_text='Dante transmit channel count from protocol query', null=True),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='event_type',
            field=models.CharField(choices=[('ONLINE', 'Came online'), ('OFFLINE', 'Went offline'), ('SCAN_STARTED', 'Network scan started'), ('MONITOR_STARTED', 'Monitor started'), ('PORT_DOWN', 'Switch port went down'), ('PORT_UP', 'Switch port came up'), ('BW_WARNING', 'Bandwidth threshold exceeded'), ('BW_CRITICAL', 'Bandwidth critical threshold exceeded'), ('DANTE_DISCOVERED', 'Dante device discovered'), ('DANTE_LOST', 'Dante device lost')], max_length=30),
        ),
    ]
