# Generated by Django 5.2.4 on 2026-05-10 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0151_discovereddevice_clock_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultitrackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_daw', models.CharField(choices=[('reaper', 'Reaper'), ('nuendo_live', 'Nuendo Live')], default='reaper', max_length=20)),
                ('feed_source', models.CharField(choices=[('console_dante', 'Console Dante card'), ('rio_direct', 'RIO direct'), ('custom', 'Custom')], default='console_dante', max_length=20)),
                ('track_order_mode', models.CharField(choices=[('console', 'Console channel order'), ('dante', 'Dante stream order'), ('custom', 'Custom (drag order)')], default='console', max_length=10)),
                ('recorder_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multitrack_sessions', to='planner.console')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multitrack_sessions', to='planner.project')),
            ],
            options={
                'verbose_name': 'Multitrack Session',
                'verbose_name_plural': 'Multitrack Sessions',
                'ordering': ['-updated_at', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MultitrackTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField(default=1)),
                ('source_type', models.CharField(choices=[('input', 'Input'), ('aux', 'Aux Output'), ('matrix', 'Matrix Output'), ('stereo', 'Stereo Output'), ('manual', 'Manual')], max_length=10)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('label_override', models.CharField(blank=True, default='', max_length=100)),
                ('color_override', models.CharField(blank=True, default='', max_length=7)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='planner.multitracksession')),
            ],
            options={
                'verbose_name': 'Multitrack Track',
                'verbose_name_plural': 'Multitrack Tracks',
                'ordering': ['track_number'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='mts_track_src_idx')],
            },
        ),
    ]
