# Generated by Django 5.2.4 on 2026-05-12 22:07

import django.db.models.deletion
import planner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0152_multitrack_session_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleauxoutput',
            name='color',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Sky Blue', 'Sky Blue'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('White', 'White')], default='Blue', max_length=20),
        ),
        migrations.AddField(
            model_name='consoleinput',
            name='color',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Sky Blue', 'Sky Blue'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('White', 'White')], default='Blue', max_length=20),
        ),
        migrations.AddField(
            model_name='consolematrixoutput',
            name='color',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Sky Blue', 'Sky Blue'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('White', 'White')], default='Blue', max_length=20),
        ),
        migrations.AddField(
            model_name='consolestereooutput',
            name='color',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Sky Blue', 'Sky Blue'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('White', 'White')], default='Blue', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsoleImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to=planner.models._import_upload_to)),
                ('parsed_sections', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('committed', models.BooleanField(default=False)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='planner.console')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Console Import',
                'verbose_name_plural': 'Console Imports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
