# Generated by Django 5.2.4 on 2026-05-13 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0153_console_color_and_consoleimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultitrackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_daw', models.CharField(choices=[('reaper', 'Reaper'), ('nuendo_live', 'Nuendo Live')], max_length=20)),
                ('feed_source', models.CharField(choices=[('console_dante', 'Console Dante card'), ('rio_direct', 'RIO direct'), ('custom', 'Custom')], max_length=20)),
                ('track_order_mode', models.CharField(choices=[('console', 'Console channel order'), ('dante', 'Dante stream order'), ('custom', 'Custom (drag order)')], max_length=10)),
                ('recorder_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multitrack_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multitrack Template',
                'verbose_name_plural': 'Multitrack Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MultitrackTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('source_type', models.CharField(choices=[('input', 'Input'), ('aux', 'Aux Output'), ('matrix', 'Matrix Output'), ('stereo', 'Stereo Output'), ('manual', 'Manual')], max_length=10)),
                ('source_number', models.CharField(blank=True, default='', max_length=10)),
                ('label_override', models.CharField(blank=True, default='', max_length=100)),
                ('color_override', models.CharField(blank=True, default='', max_length=7)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='planner.multitracktemplate')),
            ],
            options={
                'verbose_name': 'Multitrack Template Slot',
                'verbose_name_plural': 'Multitrack Template Slots',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='multitracktemplate',
            index=models.Index(fields=['created_by'], name='mtt_owner_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multitracktemplate',
            unique_together={('created_by', 'name')},
        ),
        migrations.AddIndex(
            model_name='multitracktemplateslot',
            index=models.Index(fields=['template', 'position'], name='mtt_slot_pos_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multitracktemplateslot',
            unique_together={('template', 'position')},
        ),
    ]
