# Generated by Django 5.2.4 on 2026-05-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0154_multitrack_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleauxoutput',
            name='default_record',
            field=models.BooleanField(default=True, help_text='If True, new multitrack sessions pre-check (enable) tracks created from this channel. POL-01.'),
        ),
        migrations.AddField(
            model_name='consoleauxoutput',
            name='default_record_color',
            field=models.CharField(blank=True, default='', help_text='Optional hex seed color (#RRGGBB) for tracks created from this channel. Empty = no seed; per-track override always wins. POL-02.', max_length=7),
        ),
        migrations.AddField(
            model_name='consoleinput',
            name='default_record',
            field=models.BooleanField(default=True, help_text='If True, new multitrack sessions pre-check (enable) tracks created from this channel. POL-01.'),
        ),
        migrations.AddField(
            model_name='consoleinput',
            name='default_record_color',
            field=models.CharField(blank=True, default='', help_text='Optional hex seed color (#RRGGBB) for tracks created from this channel. Empty = no seed; per-track override always wins. POL-02.', max_length=7),
        ),
        migrations.AddField(
            model_name='consolematrixoutput',
            name='default_record',
            field=models.BooleanField(default=True, help_text='If True, new multitrack sessions pre-check (enable) tracks created from this channel. POL-01.'),
        ),
        migrations.AddField(
            model_name='consolematrixoutput',
            name='default_record_color',
            field=models.CharField(blank=True, default='', help_text='Optional hex seed color (#RRGGBB) for tracks created from this channel. Empty = no seed; per-track override always wins. POL-02.', max_length=7),
        ),
        migrations.AddField(
            model_name='consolestereooutput',
            name='default_record',
            field=models.BooleanField(default=True, help_text='If True, new multitrack sessions pre-check (enable) tracks created from this channel. POL-01.'),
        ),
        migrations.AddField(
            model_name='consolestereooutput',
            name='default_record_color',
            field=models.CharField(blank=True, default='', help_text='Optional hex seed color (#RRGGBB) for tracks created from this channel. Empty = no seed; per-track override always wins. POL-02.', max_length=7),
        ),
    ]
