# Generated by Django 5.2.4 on 2026-05-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0155_channel_record_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='parent_console',
        ),
    ]
