# Generated by Django 5.2.4 on 2026-05-15 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0156_remove_device_parent_console'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_crews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crews',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.crew')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crew Member',
                'verbose_name_plural': 'Crew Members',
                'ordering': ['added_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('email__isnull', True), ('user__isnull', False)), models.Q(('email__isnull', False), ('user__isnull', True)), _connector='OR'), name='crewmember_user_xor_email'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('crew', 'user'), name='uniq_crewmember_crew_user'), models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('crew', 'email'), name='uniq_crewmember_crew_email')],
            },
        ),
        migrations.CreateModel(
            name='CrewProjectAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_adds', to='planner.crew')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_adds', to='planner.project')),
            ],
            options={
                'verbose_name': 'Crew Project Add',
                'verbose_name_plural': 'Crew Project Adds',
                'ordering': ['-added_at'],
                'unique_together': {('crew', 'project')},
            },
        ),
    ]
