# Generated by Django 5.2.4 on 2026-05-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0157_crew_crewmember_crewprojectadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalFlowDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('canvas_state', models.JSONField(blank=True, default=dict)),
                ('viewport', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_flow_diagrams', to='planner.project')),
            ],
            options={
                'verbose_name': 'Signal Flow Diagram',
                'verbose_name_plural': 'Signal Flow Diagrams',
                'ordering': ['-updated_at', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
