# Generated by Django 5.2.4 on 2026-05-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0158_signalflowdiagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoleauxoutput',
            name='default_record_color',
        ),
        migrations.RemoveField(
            model_name='consoleinput',
            name='default_record_color',
        ),
        migrations.RemoveField(
            model_name='consolematrixoutput',
            name='default_record_color',
        ),
        migrations.RemoveField(
            model_name='consolestereooutput',
            name='default_record_color',
        ),
        migrations.AlterField(
            model_name='consoleauxoutput',
            name='default_record',
            field=models.BooleanField(default=True, help_text='If checked, this channel appears in the multitrack picker and is pre-armed for recording. Uncheck to hide it from multitrack sessions entirely.', verbose_name='Include in multitrack'),
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='default_record',
            field=models.BooleanField(default=True, help_text='If checked, this channel appears in the multitrack picker and is pre-armed for recording. Uncheck to hide it from multitrack sessions entirely.', verbose_name='Include in multitrack'),
        ),
        migrations.AlterField(
            model_name='consolematrixoutput',
            name='default_record',
            field=models.BooleanField(default=True, help_text='If checked, this channel appears in the multitrack picker and is pre-armed for recording. Uncheck to hide it from multitrack sessions entirely.', verbose_name='Include in multitrack'),
        ),
        migrations.AlterField(
            model_name='consolestereooutput',
            name='default_record',
            field=models.BooleanField(default=True, help_text='If checked, this channel appears in the multitrack picker and is pre-armed for recording. Uncheck to hide it from multitrack sessions entirely.', verbose_name='Include in multitrack'),
        ),
    ]
