# Generated by Django 5.2.4 on 2026-05-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0160_backfill_processor_input_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxyinput',
            name='origin_device_output',
        ),
        migrations.RemoveField(
            model_name='p1input',
            name='origin_device_output',
        ),
    ]
