# Generated by Django 5.2.4 on 2026-06-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0164_pacoupler'),
    ]

    operations = [
        migrations.AddField(
            model_name='amp',
            name='preset',
            field=models.CharField(blank=True, default='', help_text="Preset name loaded on this amp (e.g., 'KS28 SUB', 'K2 MAIN')", max_length=100),
        ),
    ]
