# Generated by Django 5.2.4 on 2026-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0166_amplocation_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampchannel',
            name='channel_setting',
            field=models.CharField(blank=True, choices=[('', '---------'), ('PA_A', 'PA_A'), ('PA_B', 'PA_B'), ('PA_C', 'PA_C'), ('PA_D', 'PA_D'), ('LF_A', 'LF_A'), ('LF_B', 'LF_B'), ('LF_C', 'LF_C'), ('LF_D', 'LF_D'), ('HF_A', 'HF_A'), ('HF_B', 'HF_B'), ('HF_C', 'HF_C'), ('HF_D', 'HF_D'), ('SB_A', 'SB_A'), ('SB_B', 'SB_B'), ('SB_C', 'SB_C'), ('SB_D', 'SB_D')], default='', help_text='Speaker-zone routing label for this channel', max_length=20, verbose_name='Channel Setting'),
        ),
    ]
