# Generated by Django 5.2.4 on 2026-06-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0167_add_channel_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='amp',
            name='output_1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Output 1'),
        ),
        migrations.AddField(
            model_name='amp',
            name='output_2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Output 2'),
        ),
        migrations.AddField(
            model_name='amp',
            name='output_3',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Output 3'),
        ),
        migrations.AddField(
            model_name='amp',
            name='output_4',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Output 4'),
        ),
    ]
