# Generated by Django 5.2.4 on 2026-06-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0168_add_amp_outputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacoupler',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pafanout',
            name='fan_out_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('NL4_Y', 'NL4 Y'), ('DOFILL', 'DOFill'), ('DOSUB', 'DOSub'), ('NL8_Y', 'NL8 Y'), ('NL4_TO_NL8', 'NL4 to NL8')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pafanoutextension',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soundvisionprediction',
            name='show_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='planner.showday'),
        ),
    ]
