# Generated by Django 5.2.4 on 2026-06-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0170_la7_16i_sc32_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='micassignment',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='multi_assignments', to='planner.micgroup'),
        ),
        migrations.AddField(
            model_name='presenterslot',
            name='a2_groups',
            field=models.ManyToManyField(blank=True, related_name='slot_a2_multi_assignments', to='planner.micgroup'),
        ),
        migrations.AddField(
            model_name='presenterslot',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='slot_multi_assignments', to='planner.micgroup'),
        ),
    ]
