# Generated by Django 5.2.4 on 2026-06-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0170_la7_16i_sc32_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceHardwareOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Source Hardware Option',
                'verbose_name_plural': 'Source Hardware Options',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='consoleinput',
            name='source_hardware',
            field=models.CharField(blank=True, help_text='Pick from the shared Source Hardware list. Manage entries via the Source Hardware Options admin page.', max_length=50, null=True, verbose_name='Source Hardware'),
        ),
    ]
