# Generated by Django 5.2.4 on 2026-07-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0172_seed_mic_groups_m2m'),
        ('planner', '0174_seed_source_hardware_options'),
    ]

    operations = [
    ]
