# Generated by Django 5.2.4 on 2026-07-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0175_merge_20260701_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampchannel',
            name='avb_stream',
            field=models.CharField(blank=True, help_text='AVB stream assignment', max_length=120, null=True, verbose_name='AVB Stream'),
        ),
    ]
