# Generated by Django 5.2.4 on 2026-07-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0177_remove_prep_daily_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochecklist',
            name='num_days',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='audiochecklisttask',
            name='day_statuses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
