# Generated by Django 5.2.4 on 2026-08-14 23:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0179_backfill_daily_day_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='micsession',
            name='name_color',
            field=colorfield.fields.ColorField(blank=True, default='', help_text='Optional highlight color for the session name in the Mic Tracker. Leave blank for default styling.', image_field=None, max_length=25, samples=None),
        ),
    ]
