# Generated by Django 5.2.4 on 2026-08-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0180_micsession_name_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenterslot',
            name='headset_color',
            field=models.CharField(blank=True, choices=[('', '---'), ('BEIGE', 'Beige'), ('BROWN', 'Brown'), ('BLACK', 'Black')], max_length=10),
        ),
    ]
