# Generated by Django 5.2.4 on 2026-08-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0181_presenterslot_headset_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pafanout',
            name='fan_out_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('NL4_Y', 'NL4 Y'), ('DOFILL', 'DOFill'), ('DOSUB', 'DOSub'), ('NL8_Y', 'NL8 Y'), ('NL4_TO_NL8', 'NL8 to 2XNL4'), ('NL8_TO_4XNL2', 'NL8 to 4XNL2')], max_length=20),
        ),
    ]
