# Generated by Django 5.2.4 on 2026-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0183_alter_pafanout_fan_out_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pafanout',
            name='fan_out_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('NL4_Y', 'NL4 Y'), ('NL4_TO_2XNL2', 'NL4 to 2XNL2'), ('NL8_Y', 'NL8 Y'), ('NL4_TO_NL8', 'NL8 to 2XNL4'), ('NL8_TO_4XNL2', 'NL8 to 4XNL2'), ('DOFILL', 'DOFill'), ('DOSUB', 'DOSub')], max_length=20),
        ),
    ]
