# Generated by Django 5.2.4 on 2026-09-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0184_alter_pafanout_fan_out_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audiochecklisttemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='audiochecklisttemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='planner.project'),
        ),
    ]
