# Generated by Django 5.2.4 on 2026-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0185_alter_audiochecklisttemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleinput',
            name='source_hardware_b',
            field=models.CharField(blank=True, help_text="Alternate 'B' input source for this channel (e.g. a wireless backup). Modern consoles offer an A and B input per channel; A is the primary. Pick from the same shared Source Hardware list.", max_length=50, null=True, verbose_name='Source Hardware (B)'),
        ),
    ]
