# Generated by Django 5.2.4 on 2026-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0186_consoleinput_source_hardware_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleinput',
            name='source_b',
            field=models.CharField(blank=True, help_text="Alternate 'B' input source name for this channel, independent of the A source.", max_length=100, null=True, verbose_name='Source (B)'),
        ),
    ]
