# Generated by Django 5.2.4 on 2026-09-09 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0187_consoleinput_source_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacableschedule',
            name='amp',
            field=models.ForeignKey(blank=True, help_text='Amplifier from the Amplifier Reference module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_cables', to='planner.amp', verbose_name='Destination amp (linked)'),
        ),
        migrations.AddField(
            model_name='pacableschedule',
            name='entry_mode',
            field=models.CharField(choices=[('text', 'Free text'), ('linked', 'From Soundvision / Amps')], default='text', help_text="'From Soundvision / Amps' links this cable to a Speaker Array and an Amp; 'Free text' uses the plain Array/Speaker and Destination fields.", max_length=10, verbose_name='Entry mode'),
        ),
        migrations.AddField(
            model_name='pacableschedule',
            name='speaker_array',
            field=models.ForeignKey(blank=True, help_text='Speaker array or single speaker from the imported Soundvision report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_cables', to='planner.speakerarray', verbose_name='Array / Speaker (linked)'),
        ),
    ]
