# Generated by Django 5.2.4 on 2026-09-16
# Modified: 3-step migration to add a unique listen_token to existing rows
# (mirrors 0149_project_agent_api_key). Issue #74.

import django.core.validators
import uuid
from django.db import migrations, models


def generate_unique_listen_tokens(apps, schema_editor):
    """Assign a unique UUID listen_token to each existing project."""
    Project = apps.get_model('planner', 'Project')
    for project in Project.objects.all():
        project.listen_token = uuid.uuid4()
        project.save(update_fields=['listen_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0188_pacableschedule_amp_pacableschedule_entry_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micassignment',
            name='input_channel',
            field=models.PositiveIntegerField(blank=True, help_text='Audio input channel on the Listen companion device. Defaults to the RF/slot number when blank.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        # Step 1: add listen_token without the unique constraint
        migrations.AddField(
            model_name='project',
            name='listen_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True,
                                   help_text='Pairing token for the A2 Listen companion app (Issue #74)'),
        ),
        # Step 2: populate unique values for existing rows
        migrations.RunPython(generate_unique_listen_tokens, migrations.RunPython.noop),
        # Step 3: enforce the unique constraint
        migrations.AlterField(
            model_name='project',
            name='listen_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                   help_text='Pairing token for the A2 Listen companion app (Issue #74)'),
        ),
    ]
