# Generated by Django 5.2.4 on 2026-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0189_micassignment_input_channel_project_listen_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='listen_status',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='listen_status_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
