# Generated by Django 5.2.4 on 2026-10-02 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0190_project_listen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacableschedule',
            name='destination',
            field=models.CharField(default='', help_text="e.g., 'SL Amp Rack', 'SL Amp Rack 1', 'FOH Amp Rack'", max_length=50, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='pacableschedule',
            name='label',
            field=models.ForeignKey(blank=True, help_text='PA Zone label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cables', to='planner.pazone', verbose_name='Label'),
        ),
    ]
