# Generated by Django 5.2.4 on 2026-10-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0191_alter_pacableschedule_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commbeltpack',
            name='manufacturer',
            field=models.CharField(choices=[('clearcom_helixnet', 'Clear-Com HelixNet'), ('clearcom_arcadia', 'Clear-Com Arcadia'), ('rts_partyline', 'RTS Partyline'), ('rts_odin', 'RTS ODIN Matrix'), ('riedel_performer', 'Riedel Performer'), ('clearcom_freespeak', 'Clear-Com FreeSpeak Edge/Icon'), ('clearcom_freespeak_ii', 'Clear-Com FreeSpeak II'), ('riedel_bolero', 'Riedel Bolero'), ('rad_uv1g', 'Radio Active Designs RAD')], default='clearcom_helixnet', help_text='Belt pack system manufacturer', max_length=50, verbose_name='System/Manufacturer'),
        ),
    ]
