# Generated by Django 5.2.4 on 2026-10-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0192_alter_commbeltpack_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commbeltpack',
            options={'ordering': ['system_type', 'bp_number'], 'verbose_name': 'Comm Device', 'verbose_name_plural': 'Comm Devices'},
        ),
        migrations.AlterField(
            model_name='commbeltpack',
            name='checked_out',
            field=models.BooleanField(default=False, help_text='Whether this device has been checked out (Wireless only)'),
        ),
        migrations.AlterField(
            model_name='commbeltpack',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address for hardwired devices (optional)', null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='commbeltpack',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('clearcom_helixnet', 'Clear-Com HelixNet'), ('rts_partyline', 'RTS Partyline'), ('rts_odin', 'RTS ODIN Matrix'), ('riedel_performer', 'Riedel Performer'), ('clearcom_freespeak', 'Clear-Com FreeSpeak Edge/Icon'), ('clearcom_freespeak_ii', 'Clear-Com FreeSpeak II'), ('riedel_bolero', 'Riedel Bolero'), ('rad_uv1g', 'Radio Active Designs RAD')], default='clearcom_helixnet', help_text='Superseded by Model.', max_length=50, verbose_name='System/Manufacturer (legacy)'),
        ),
        migrations.AlterField(
            model_name='commbeltpack',
            name='unit_location',
            field=models.ForeignKey(blank=True, help_text='Equipment location for this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_beltpacks', to='planner.location', verbose_name='Location'),
        ),
        migrations.CreateModel(
            name='CommDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='Groups the dropdown, e.g. Clear-Com, RTS, Riedel', max_length=80)),
                ('name', models.CharField(help_text='The device as it is written on the device, e.g. FSII-BP19', max_length=120, verbose_name='Model')),
                ('device_type', models.CharField(choices=[('WIRELESS_BP', 'Wireless Beltpack'), ('WIRED_BP', 'Wired Beltpack'), ('KEY_PANEL', 'Key Panel'), ('STATION', 'Speaker/Remote Station')], max_length=20)),
                ('default_channel_count', models.PositiveIntegerField(default=0, help_text='Channel keys this device carries. 0 if not known.', verbose_name='Default channel count')),
                ('is_active', models.BooleanField(default=True, help_text='Unticking hides it from the dropdown without deleting it, so devices already recorded against it keep their model.')),
            ],
            options={
                'verbose_name': 'Comm Device Model',
                'verbose_name_plural': 'Comm Device Models',
                'ordering': ['manufacturer', 'name'],
                'constraints': [models.UniqueConstraint(fields=('manufacturer', 'name'), name='unique_comm_device_model')],
            },
        ),
        migrations.AddField(
            model_name='commbeltpack',
            name='device_model',
            field=models.ForeignKey(blank=True, help_text='The device itself. System Type follows from its device type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='planner.commdevicemodel', verbose_name='Model'),
        ),
    ]
