# Generated by Django 5.2.4 on 2026-10-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0194_seed_comm_device_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commbeltpack',
            name='bp_number',
            field=models.IntegerField(verbose_name='Device #'),
        ),
        migrations.AlterField(
            model_name='commbeltpackchannel',
            name='channel_number',
            field=models.PositiveIntegerField(verbose_name='Channel #'),
        ),
    ]
