# Generated by Django 5.2.4 on 2026-10-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0195_device_number_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pafanoutextension',
            name='extension_length',
            field=models.IntegerField(choices=[(25, "25'"), (50, "50'"), (100, "100'"), (150, "150'")], verbose_name='Extension Length'),
        ),
    ]
