# Generated by Django 5.2.4 on 2026-10-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0198_unique_amp_channel_and_rf_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenterPhoto',
            fields=[
                ('presenter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='headshot', serialize=False, to='planner.presenter')),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=32)),
                ('sha256', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presenter Photo',
            },
        ),
    ]
